<Global.Microsoft.VisualBasic.CompilerServices.DesignerGenerated()> _
Partial Class FormControls
    Inherits System.Windows.Forms.Form

    'Form overrides dispose to clean up the component list.
    <System.Diagnostics.DebuggerNonUserCode()> _
    Protected Overrides Sub Dispose(ByVal disposing As Boolean)
        Try
            If disposing AndAlso components IsNot Nothing Then
                components.Dispose()
            End If
        Finally
            MyBase.Dispose(disposing)
        End Try
    End Sub

    'Required by the Windows Form Designer
    Private components As System.ComponentModel.IContainer

    'NOTE: The following procedure is required by the Windows Form Designer
    'It can be modified using the Windows Form Designer.  
    'Do not modify it using the code editor.
    <System.Diagnostics.DebuggerStepThrough()> _
    Private Sub InitializeComponent()
        Dim resources As System.ComponentModel.ComponentResourceManager = New System.ComponentModel.ComponentResourceManager(GetType(FormControls))
        Me.groupBox1 = New System.Windows.Forms.GroupBox
        Me.rdbExcel2010 = New System.Windows.Forms.RadioButton
        Me.rdbExcel2007 = New System.Windows.Forms.RadioButton
        Me.rdbExcel97 = New System.Windows.Forms.RadioButton
        Me.label2 = New System.Windows.Forms.Label
        Me.pictureBox1 = New System.Windows.Forms.PictureBox
        Me.btnCreate = New System.Windows.Forms.Button
        Me.PictureBox2 = New System.Windows.Forms.PictureBox
        Me.rdbExcel2013 = New System.Windows.Forms.RadioButton
        Me.groupBox1.SuspendLayout()
        CType(Me.pictureBox1, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.PictureBox2, System.ComponentModel.ISupportInitialize).BeginInit()
        Me.SuspendLayout()
        '
        'groupBox1
        '
        Me.groupBox1.Controls.Add(Me.rdbExcel2013)
        Me.groupBox1.Controls.Add(Me.rdbExcel2010)
        Me.groupBox1.Controls.Add(Me.rdbExcel2007)
        Me.groupBox1.Controls.Add(Me.rdbExcel97)
        Me.groupBox1.Font = New System.Drawing.Font("Microsoft Sans Serif", 8.25!, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, CType(0, Byte))
        Me.groupBox1.Location = New System.Drawing.Point(12, 158)
        Me.groupBox1.Name = "groupBox1"
        Me.groupBox1.Size = New System.Drawing.Size(326, 37)
        Me.groupBox1.TabIndex = 79
        Me.groupBox1.TabStop = False
        Me.groupBox1.Text = "Save As"
        '
        'rdbExcel2010
        '
        Me.rdbExcel2010.AutoSize = True
        Me.rdbExcel2010.Font = New System.Drawing.Font("Microsoft Sans Serif", 8.25!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, CType(0, Byte))
        Me.rdbExcel2010.Location = New System.Drawing.Point(164, 13)
        Me.rdbExcel2010.Name = "rdbExcel2010"
        Me.rdbExcel2010.Size = New System.Drawing.Size(78, 17)
        Me.rdbExcel2010.TabIndex = 2
        Me.rdbExcel2010.TabStop = True
        Me.rdbExcel2010.Text = "Excel 2010"
        Me.rdbExcel2010.UseVisualStyleBackColor = True
        '
        'rdbExcel2007
        '
        Me.rdbExcel2007.AutoSize = True
        Me.rdbExcel2007.Font = New System.Drawing.Font("Microsoft Sans Serif", 8.25!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, CType(0, Byte))
        Me.rdbExcel2007.Location = New System.Drawing.Point(85, 13)
        Me.rdbExcel2007.Name = "rdbExcel2007"
        Me.rdbExcel2007.Size = New System.Drawing.Size(78, 17)
        Me.rdbExcel2007.TabIndex = 1
        Me.rdbExcel2007.Text = "Excel 2007"
        Me.rdbExcel2007.UseVisualStyleBackColor = True
        '
        'rdbExcel97
        '
        Me.rdbExcel97.AutoSize = True
        Me.rdbExcel97.Checked = True
        Me.rdbExcel97.Font = New System.Drawing.Font("Microsoft Sans Serif", 8.25!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, CType(0, Byte))
        Me.rdbExcel97.Location = New System.Drawing.Point(6, 13)
        Me.rdbExcel97.Name = "rdbExcel97"
        Me.rdbExcel97.Size = New System.Drawing.Size(75, 17)
        Me.rdbExcel97.TabIndex = 0
        Me.rdbExcel97.TabStop = True
        Me.rdbExcel97.Text = "Excel2003"
        Me.rdbExcel97.UseVisualStyleBackColor = True
        '
        'label2
        '
        Me.label2.Anchor = System.Windows.Forms.AnchorStyles.None
        Me.label2.Font = New System.Drawing.Font("Verdana", 8.25!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, CType(161, Byte))
        Me.label2.ForeColor = System.Drawing.SystemColors.ControlText
        Me.label2.Location = New System.Drawing.Point(0, 96)
        Me.label2.Name = "label2"
        Me.label2.Size = New System.Drawing.Size(429, 48)
        Me.label2.TabIndex = 77
        Me.label2.Text = "Click the button to view an Excel spreadsheet generated by Essential XlsIO. Pleas" & _
            "e note that MS Excel Viewer or MS Excel is required to view the resultant docume" & _
            "nt."
        '
        'pictureBox1
        '
        Me.pictureBox1.Image = CType(resources.GetObject("pictureBox1.Image"), System.Drawing.Image)
        Me.pictureBox1.Location = New System.Drawing.Point(59, -3)
        Me.pictureBox1.Name = "pictureBox1"
        Me.pictureBox1.Size = New System.Drawing.Size(377, 96)
        Me.pictureBox1.TabIndex = 76
        Me.pictureBox1.TabStop = False
        '
        'btnCreate
        '
        Me.btnCreate.Anchor = CType((System.Windows.Forms.AnchorStyles.Top Or System.Windows.Forms.AnchorStyles.Right), System.Windows.Forms.AnchorStyles)
        Me.btnCreate.BackColor = System.Drawing.Color.Transparent
        Me.btnCreate.Font = New System.Drawing.Font("Verdana", 8.25!)
        Me.btnCreate.Image = CType(resources.GetObject("btnCreate.Image"), System.Drawing.Image)
        Me.btnCreate.ImageAlign = System.Drawing.ContentAlignment.MiddleRight
        Me.btnCreate.Location = New System.Drawing.Point(344, 166)
        Me.btnCreate.Name = "btnCreate"
        Me.btnCreate.Size = New System.Drawing.Size(85, 26)
        Me.btnCreate.TabIndex = 75
        Me.btnCreate.Text = "Create"
        Me.btnCreate.UseVisualStyleBackColor = False
        '
        'PictureBox2
        '
        Me.PictureBox2.Image = CType(resources.GetObject("PictureBox2.Image"), System.Drawing.Image)
        Me.PictureBox2.Location = New System.Drawing.Point(-3, -13)
        Me.PictureBox2.Name = "PictureBox2"
        Me.PictureBox2.Size = New System.Drawing.Size(91, 96)
        Me.PictureBox2.TabIndex = 80
        Me.PictureBox2.TabStop = False
        '
        'rdbExcel2013
        '
        Me.rdbExcel2013.AutoSize = True
        Me.rdbExcel2013.Font = New System.Drawing.Font("Microsoft Sans Serif", 8.25!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, CType(0, Byte))
        Me.rdbExcel2013.Location = New System.Drawing.Point(241, 13)
        Me.rdbExcel2013.Name = "rdbExcel2013"
        Me.rdbExcel2013.Size = New System.Drawing.Size(78, 17)
        Me.rdbExcel2013.TabIndex = 3
        Me.rdbExcel2013.TabStop = True
        Me.rdbExcel2013.Text = "Excel 2013"
        Me.rdbExcel2013.UseVisualStyleBackColor = True
        '
        'FormControls
        '
        Me.AutoScaleDimensions = New System.Drawing.SizeF(6.0!, 13.0!)
        Me.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font
        Me.BackColor = System.Drawing.Color.White
        Me.ClientSize = New System.Drawing.Size(433, 218)
        Me.Controls.Add(Me.pictureBox1)
        Me.Controls.Add(Me.PictureBox2)
        Me.Controls.Add(Me.btnCreate)
        Me.Controls.Add(Me.groupBox1)
        Me.Controls.Add(Me.label2)
        Me.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedSingle
        Me.Icon = CType(resources.GetObject("$this.Icon"), System.Drawing.Icon)
        Me.MaximizeBox = False
        Me.MinimizeBox = False
        Me.Name = "FormControls"
        Me.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen
        Me.Text = "Form Controls"
        Me.groupBox1.ResumeLayout(False)
        Me.groupBox1.PerformLayout()
        CType(Me.pictureBox1, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.PictureBox2, System.ComponentModel.ISupportInitialize).EndInit()
        Me.ResumeLayout(False)

    End Sub
    Private WithEvents groupBox1 As System.Windows.Forms.GroupBox
    Private WithEvents rdbExcel2007 As System.Windows.Forms.RadioButton
    Private WithEvents rdbExcel97 As System.Windows.Forms.RadioButton
    Private WithEvents label2 As System.Windows.Forms.Label
    Private WithEvents pictureBox1 As System.Windows.Forms.PictureBox
    Private WithEvents btnCreate As System.Windows.Forms.Button
    Friend WithEvents rdbExcel2010 As System.Windows.Forms.RadioButton
    Friend WithEvents rdbExcel2013 As System.Windows.Forms.RadioButton
    Private WithEvents PictureBox2 As System.Windows.Forms.PictureBox

End Class
