Option Strict On
Option Explicit On
Imports System
'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.42
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Namespace My.Resources

	'This class was auto-generated by the StronglyTypedResourceBuilder
	'class via a tool like ResGen or Visual Studio.
	'To add or remove a member, edit your .ResX file then rerun ResGen
	'with the /str option, or rebuild your VS project.
	'''<summary>
	'''  A strongly-typed resource class, for looking up localized strings, etc.
	'''</summary>
	<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"), _
	 Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
	 Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(), _
	 Global.Microsoft.VisualBasic.HideModuleNameAttribute()> _
	Friend Module Resources

		Private resourceMan As Global.System.Resources.ResourceManager

		Private resourceCulture As Global.System.Globalization.CultureInfo

		'''<summary>
		'''  Returns the cached ResourceManager instance used by this class.
		'''</summary>
		<Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
		Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
			Get
				If Object.ReferenceEquals(resourceMan, Nothing) Then
					Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Word2007Demo_2005.Resources", GetType(Resources).Assembly)
					resourceMan = temp
				End If
				Return resourceMan
			End Get
		End Property

		'''<summary>
		'''  Overrides the current thread's CurrentUICulture property for all
		'''  resource lookups using this strongly typed resource class.
		'''</summary>
		<Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
		Friend Property Culture() As Global.System.Globalization.CultureInfo
			Get
				Return resourceCulture
			End Get
			Set(ByVal value As Global.System.Globalization.CultureInfo)
				resourceCulture = Value
			End Set
		End Property

		Friend ReadOnly Property close_icon() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("close_icon", resourceCulture)
				Return CType(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend ReadOnly Property exitword_icon_16() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("exitword_icon_16", resourceCulture)
				Return CType(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend ReadOnly Property help() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("help", resourceCulture)
				Return CType(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend ReadOnly Property new_icon() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("new_icon", resourceCulture)
				Return CType(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend ReadOnly Property open_icon() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("open_icon", resourceCulture)
				Return CType(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend ReadOnly Property prepare_icon() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("prepare_icon", resourceCulture)
				Return CType(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend ReadOnly Property printer_icon() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("printer_icon", resourceCulture)
				Return CType(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend ReadOnly Property publish_blog_icon() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("publish_blog_icon", resourceCulture)
				Return CType(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend ReadOnly Property save_icon() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("save_icon", resourceCulture)
				Return CType(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend ReadOnly Property saveas_icon() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("saveas_icon", resourceCulture)
				Return CType(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend ReadOnly Property send_icon() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("send_icon", resourceCulture)
				Return CType(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend ReadOnly Property wordoptions_icon_16() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("wordoptions_icon_16", resourceCulture)
				Return CType(obj, System.Drawing.Bitmap)
			End Get
		End Property
	End Module
End Namespace
