'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.5456
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------


Imports Microsoft.VisualBasic
Imports System

Namespace My.Resources


	''' <summary>
	'''   A strongly-typed resource class, for looking up localized strings, etc.
	''' </summary>
	' This class was auto-generated by the StronglyTypedResourceBuilder
	' class via a tool like ResGen or Visual Studio.
	' To add or remove a member, edit your .ResX file then rerun ResGen
	' with the /str option, or rebuild your VS project.
	<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"), Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(), _
	Global.Microsoft.VisualBasic.HideModuleNameAttribute()> _
	Friend Module Resources

		Private resourceMan As Global.System.Resources.ResourceManager

		Private resourceCulture As Global.System.Globalization.CultureInfo

'		internal Resources()
'		{
'		}

		''' <summary>
		'''   Returns the cached ResourceManager instance used by this class.
		''' </summary>
		<Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
		Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
			Get
				If Object.ReferenceEquals(resourceMan, Nothing) Then
					Dim temp As New Global.System.Resources.ResourceManager("Resources", GetType(Resources).Assembly)
					resourceMan = temp
				End If
				Return resourceMan
			End Get
		End Property

		''' <summary>
		'''   Overrides the current thread's CurrentUICulture property for all
		'''   resource lookups using this strongly typed resource class.
		''' </summary>
		<Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
		Friend Property Culture() As Global.System.Globalization.CultureInfo
			Get
				Return resourceCulture
			End Get
			Set(ByVal value As System.Globalization.CultureInfo)
				resourceCulture = value
			End Set
		End Property

		Friend ReadOnly Property AutoComplete() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("AutoComplete", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property AutoLabel() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("AutoLabel", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property BackStageView() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("BackStageView", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property BannerTextProvider() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("BannerTextProvider", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property BarControl() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("BarControl", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property Birds() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("Birds", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property BlankPage32() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("BlankPage32", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property Bold16() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("Bold16", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property BorderLayout() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("BorderLayout", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property Boxes3D() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("Boxes3D", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property ButtonAdv() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("ButtonAdv", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property ButtonEdit() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("ButtonEdit", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property CalculatorControl() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("CalculatorControl", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property CardLayout() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("CardLayout", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property CheckBoxAdv() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("CheckBoxAdv", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property CheckBoxItem() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("CheckBoxItem", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property ChildFrameBarManager() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("ChildFrameBarManager", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property ClearFormatting16() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("ClearFormatting16", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property Clock() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("Clock", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property Close32() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("Close32", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property ColorPickerButton() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("ColorPickerButton", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property ColorPickerUIAdv() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("ColorPickerUIAdv", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property ColorUIAdv() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("ColorUIAdv", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property ColorUIControl() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("ColorUIControl", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property ComboBoxAdv() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("ComboBoxAdv", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property ComboBoxAutoComplete() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("ComboBoxAutoComplete", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property ComboBoxBase() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("ComboBoxBase", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property ComboDropDown() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("ComboDropDown", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property ComboListBox() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("ComboListBox", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property commandbarcontroller() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("commandbarcontroller", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property ContextMenuStripEx() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("ContextMenuStripEx", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property CoverPage32() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("CoverPage32", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property CurrencyEdit() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("CurrencyEdit", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property CurrencyTextBox() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("CurrencyTextBox", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property CurrencyTextBox1() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("CurrencyTextBox1", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property DateTimePickerExt() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("DateTimePickerExt", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property docking() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("docking", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property dockingpanel() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("dockingpanel", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property DomainUpDownExt() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("DomainUpDownExt", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property DoubleTextBox() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("DoubleTextBox", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property EditableList() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("EditableList", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property [Exit]() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("Exit", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property FlowLayout() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("FlowLayout", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property FolderBrowser() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("FolderBrowser", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property FontColor16() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("FontColor16", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property FontComboBox() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("FontComboBox", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property FontListBox() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("FontListBox", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property Gallery() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("Gallery", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property GradientLabel() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("GradientLabel", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property GradientPanel() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("GradientPanel", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property GradientPanelExt() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("GradientPanelExt", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property GridBagLayout() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("GridBagLayout", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property GridLayout() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("GridLayout", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property groupbar() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("groupbar", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property groupviewcontrol() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("groupviewcontrol", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property GrowFont16() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("GrowFont16", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property Imagelistadv() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("Imagelistadv", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property ImageStreamer() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("ImageStreamer", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property IntegerTextBox() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("IntegerTextBox", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property Italic16() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("Italic16", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property MainFrameBarManager() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("MainFrameBarManager", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property MaskedEditBox() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("MaskedEditBox", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property MaskedEditBox1() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("MaskedEditBox1", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property MiniToolBar() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("MiniToolBar", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property MonthCalendarExt() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("MonthCalendarExt", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property MultiColumnTreeView() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("MultiColumnTreeView", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property NavigationView() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("NavigationView", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property NumericUpDownExt() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("NumericUpDownExt", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property OfficeButton() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("OfficeButton", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property OfficeDropDownButton() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("OfficeDropDownButton", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property OfficeSplitButton() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("OfficeSplitButton", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property Open32() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("Open32", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property Options() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("Options", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property PageBreak32() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("PageBreak32", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property PercentTextBox() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("PercentTextBox", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property Picture32() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("Picture32", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property PopupControlContainer() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("PopupControlContainer", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property PopupMenu() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("PopupMenu", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property PopupMenusManager() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("PopupMenusManager", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property ProgressBarEx() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("ProgressBarEx", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property ProgressBarEx1() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("ProgressBarEx1", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property RadioButtonAdv() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("RadioButtonAdv", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property RadioButtonItem() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("RadioButtonItem", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property RecordNavigationBar() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("RecordNavigationBar", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property RecordNavigationControl() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("RecordNavigationControl", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property Refresh() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("Refresh", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property Refresh1() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("Refresh1", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property RibbonControlAdv() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("RibbonControlAdv", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property RibbonPanelMergeContainer() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("RibbonPanelMergeContainer", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property RibbonTabControl() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("RibbonTabControl", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property sample() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("sample", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property sample1() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("sample1", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property sample2() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("sample2", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property Save16() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("Save16", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property Save32() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("Save32", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property SaveAs32() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("SaveAs32", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property ScrollersFrame() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("ScrollersFrame", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property Search_Tools() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("Search Tools", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property Search_Tools1() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("Search Tools1", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property Search_Tools2() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("Search Tools2", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property Search_Tools3() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("Search Tools3", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property Search_Tools4() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("Search Tools4", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property Search_Tools5() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("Search Tools5", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property ShrinkFont16() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("ShrinkFont16", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property SkinManager() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("SkinManager", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property Slider() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("Slider", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property SpellChecker() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("SpellChecker", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property SplashControl() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("SplashControl", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property SplashPanel() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("SplashPanel", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property SplitButton() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("SplitButton", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property SplitContainerAdv() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("SplitContainerAdv", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property SplitterControl() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("SplitterControl", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property StatusBarAdv() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("StatusBarAdv", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property StatusBarAdvPanel() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("StatusBarAdvPanel", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property StatusStripEx() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("StatusStripEx", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property Strikethrough16() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("Strikethrough16", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property Subscript16() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("Subscript16", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property SuperAccelerator() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("SuperAccelerator", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property Superscript16() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("Superscript16", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property TabBarSplitterControl() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("TabBarSplitterControl", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property TabbedGroup() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("TabbedGroup", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property TabbedMDIManager() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("TabbedMDIManager", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property TabControlExt() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("TabControlExt", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property TabSplitterContainer() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("TabSplitterContainer", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property TextBoxExt() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("TextBoxExt", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property TextHighlightColor16() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("TextHighlightColor16", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property TextHighlightColor161() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("TextHighlightColor161", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property TileLayout() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("TileLayout", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property ToolStripComboBoxEx() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("ToolStripComboBoxEx", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property ToolStripEx() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("ToolStripEx", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property ToolStripPanelItem() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("ToolStripPanelItem", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property ToolStripSplitButtonEx() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("ToolStripSplitButtonEx", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property ToolTip() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("ToolTip", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property TrackBarEx() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("TrackBarEx", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property TreeViewAdv() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("TreeViewAdv", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property TypeLoader() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("TypeLoader", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property Underline16() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("Underline16", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property WizardControl() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("WizardControl", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property XPTaskBar() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("XPTaskBar", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property XPTaskBarBox() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("XPTaskBarBox", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property XPTaskPane() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("XPTaskPane", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property XPToolBar() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("XPToolBar", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property
	End Module
End Namespace
