<Global.Microsoft.VisualBasic.CompilerServices.DesignerGenerated()> _
Partial Class PivotTable
    Inherits System.Windows.Forms.Form

    'Form overrides dispose to clean up the component list.
    <System.Diagnostics.DebuggerNonUserCode()> _
    Protected Overrides Sub Dispose(ByVal disposing As Boolean)
        If disposing AndAlso components IsNot Nothing Then
            components.Dispose()
        End If
        MyBase.Dispose(disposing)
    End Sub

    'Required by the Windows Form Designer
    Private components As System.ComponentModel.IContainer

    'NOTE: The following procedure is required by the Windows Form Designer
    'It can be modified using the Windows Form Designer.  
    'Do not modify it using the code editor.
    <System.Diagnostics.DebuggerStepThrough()> _
    Private Sub InitializeComponent()
        Dim resources As System.ComponentModel.ComponentResourceManager = New System.ComponentModel.ComponentResourceManager(GetType(PivotTable))
        Me.label2 = New System.Windows.Forms.Label()
        Me.pictureBox1 = New System.Windows.Forms.PictureBox()
        Me.btnCustomize = New System.Windows.Forms.Button()
        Me.groupBox1 = New System.Windows.Forms.GroupBox()
        Me.rdbExcel2010 = New System.Windows.Forms.RadioButton()
        Me.rdbExcel2007 = New System.Windows.Forms.RadioButton()
        Me.btnCreate = New System.Windows.Forms.Button()
        Me.GroupBox2 = New System.Windows.Forms.GroupBox()
        Me.ckbMultiplePageFilter = New System.Windows.Forms.CheckBox()
        Me.ckbPageFilter = New System.Windows.Forms.CheckBox()
        Me.GroupBox3 = New System.Windows.Forms.GroupBox()
        Me.GroupBox4 = New System.Windows.Forms.GroupBox()
        Me.rdbRCValueFilter = New System.Windows.Forms.RadioButton()
        Me.rdbRCMultileFilter = New System.Windows.Forms.RadioButton()
        Me.rdbRCLabelFilter = New System.Windows.Forms.RadioButton()
        Me.ckbColumnFilter = New System.Windows.Forms.CheckBox()
        Me.ckbRowFilter = New System.Windows.Forms.CheckBox()
        Me.rdbExcel2013 = New System.Windows.Forms.RadioButton()
        CType(Me.pictureBox1, System.ComponentModel.ISupportInitialize).BeginInit()
        Me.groupBox1.SuspendLayout()
        Me.GroupBox2.SuspendLayout()
        Me.GroupBox3.SuspendLayout()
        Me.GroupBox4.SuspendLayout()
        Me.SuspendLayout()
        '
        'label2
        '
        Me.label2.Font = New System.Drawing.Font("Verdana", 8.25!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, CType(161, Byte))
        Me.label2.ForeColor = System.Drawing.SystemColors.ControlText
        Me.label2.Location = New System.Drawing.Point(0, 109)
        Me.label2.Name = "label2"
        Me.label2.Size = New System.Drawing.Size(372, 48)
        Me.label2.TabIndex = 76
        Me.label2.Text = "Click the button to view an Excel spreadsheet generated by Essential XlsIO. Pleas" & _
    "e note that MS Excel Viewer or MS Excel is required to view the resultant docume" & _
    "nt."
        Me.label2.TextAlign = System.Drawing.ContentAlignment.MiddleLeft
        '
        'pictureBox1
        '
        Me.pictureBox1.Dock = System.Windows.Forms.DockStyle.Top
        Me.pictureBox1.Image = CType(resources.GetObject("pictureBox1.Image"), System.Drawing.Image)
        Me.pictureBox1.Location = New System.Drawing.Point(0, 0)
        Me.pictureBox1.Name = "pictureBox1"
        Me.pictureBox1.Size = New System.Drawing.Size(419, 96)
        Me.pictureBox1.TabIndex = 75
        Me.pictureBox1.TabStop = False
        '
        'btnCustomize
        '
        Me.btnCustomize.Anchor = CType((System.Windows.Forms.AnchorStyles.Top Or System.Windows.Forms.AnchorStyles.Right), System.Windows.Forms.AnchorStyles)
        Me.btnCustomize.BackColor = System.Drawing.Color.Transparent
        Me.btnCustomize.Image = CType(resources.GetObject("btnCustomize.Image"), System.Drawing.Image)
        Me.btnCustomize.ImageAlign = System.Drawing.ContentAlignment.MiddleRight
        Me.btnCustomize.Location = New System.Drawing.Point(243, 311)
        Me.btnCustomize.Name = "btnCustomize"
        Me.btnCustomize.Size = New System.Drawing.Size(137, 26)
        Me.btnCustomize.TabIndex = 78
        Me.btnCustomize.Text = "Customize Pivot Table"
        Me.btnCustomize.TextAlign = System.Drawing.ContentAlignment.MiddleLeft
        Me.btnCustomize.UseVisualStyleBackColor = False
        '
        'groupBox1
        '
        Me.groupBox1.Controls.Add(Me.rdbExcel2013)
        Me.groupBox1.Controls.Add(Me.rdbExcel2010)
        Me.groupBox1.Controls.Add(Me.rdbExcel2007)
        Me.groupBox1.Font = New System.Drawing.Font("Microsoft Sans Serif", 8.25!, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, CType(0, Byte))
        Me.groupBox1.Location = New System.Drawing.Point(136, 259)
        Me.groupBox1.Name = "groupBox1"
        Me.groupBox1.Size = New System.Drawing.Size(271, 35)
        Me.groupBox1.TabIndex = 79
        Me.groupBox1.TabStop = False
        Me.groupBox1.Text = "SaveAs"
        '
        'rdbExcel2010
        '
        Me.rdbExcel2010.AutoSize = True
        Me.rdbExcel2010.Font = New System.Drawing.Font("Microsoft Sans Serif", 8.25!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, CType(0, Byte))
        Me.rdbExcel2010.Location = New System.Drawing.Point(107, 11)
        Me.rdbExcel2010.Name = "rdbExcel2010"
        Me.rdbExcel2010.Size = New System.Drawing.Size(78, 17)
        Me.rdbExcel2010.TabIndex = 1
        Me.rdbExcel2010.Text = "Excel 2010"
        Me.rdbExcel2010.UseVisualStyleBackColor = True
        '
        'rdbExcel2007
        '
        Me.rdbExcel2007.AutoSize = True
        Me.rdbExcel2007.Checked = True
        Me.rdbExcel2007.Font = New System.Drawing.Font("Microsoft Sans Serif", 8.25!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, CType(0, Byte))
        Me.rdbExcel2007.Location = New System.Drawing.Point(22, 11)
        Me.rdbExcel2007.Name = "rdbExcel2007"
        Me.rdbExcel2007.Size = New System.Drawing.Size(78, 17)
        Me.rdbExcel2007.TabIndex = 0
        Me.rdbExcel2007.TabStop = True
        Me.rdbExcel2007.Text = "Excel 2007"
        Me.rdbExcel2007.UseVisualStyleBackColor = True
        '
        'btnCreate
        '
        Me.btnCreate.Anchor = CType((System.Windows.Forms.AnchorStyles.Top Or System.Windows.Forms.AnchorStyles.Right), System.Windows.Forms.AnchorStyles)
        Me.btnCreate.BackColor = System.Drawing.Color.Transparent
        Me.btnCreate.Image = CType(resources.GetObject("btnCreate.Image"), System.Drawing.Image)
        Me.btnCreate.ImageAlign = System.Drawing.ContentAlignment.MiddleRight
        Me.btnCreate.Location = New System.Drawing.Point(76, 311)
        Me.btnCreate.Name = "btnCreate"
        Me.btnCreate.Size = New System.Drawing.Size(137, 26)
        Me.btnCreate.TabIndex = 77
        Me.btnCreate.Text = "Create Pivot Table"
        Me.btnCreate.TextAlign = System.Drawing.ContentAlignment.MiddleLeft
        Me.btnCreate.UseVisualStyleBackColor = False
        '
        'GroupBox2
        '
        Me.GroupBox2.Controls.Add(Me.ckbMultiplePageFilter)
        Me.GroupBox2.Controls.Add(Me.ckbPageFilter)
        Me.GroupBox2.Font = New System.Drawing.Font("Microsoft Sans Serif", 8.25!, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, CType(0, Byte))
        Me.GroupBox2.Location = New System.Drawing.Point(10, 165)
        Me.GroupBox2.Name = "GroupBox2"
        Me.GroupBox2.Size = New System.Drawing.Size(120, 129)
        Me.GroupBox2.TabIndex = 80
        Me.GroupBox2.TabStop = False
        Me.GroupBox2.Text = "Page Filter"
        '
        'ckbMultiplePageFilter
        '
        Me.ckbMultiplePageFilter.AutoSize = True
        Me.ckbMultiplePageFilter.Font = New System.Drawing.Font("Microsoft Sans Serif", 8.25!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, CType(0, Byte))
        Me.ckbMultiplePageFilter.Location = New System.Drawing.Point(3, 54)
        Me.ckbMultiplePageFilter.Name = "ckbMultiplePageFilter"
        Me.ckbMultiplePageFilter.Size = New System.Drawing.Size(116, 17)
        Me.ckbMultiplePageFilter.TabIndex = 1
        Me.ckbMultiplePageFilter.Text = "Apply Multiple Filter"
        Me.ckbMultiplePageFilter.UseVisualStyleBackColor = True
        '
        'ckbPageFilter
        '
        Me.ckbPageFilter.AutoSize = True
        Me.ckbPageFilter.Font = New System.Drawing.Font("Microsoft Sans Serif", 8.25!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, CType(0, Byte))
        Me.ckbPageFilter.Location = New System.Drawing.Point(3, 28)
        Me.ckbPageFilter.Name = "ckbPageFilter"
        Me.ckbPageFilter.Size = New System.Drawing.Size(76, 17)
        Me.ckbPageFilter.TabIndex = 0
        Me.ckbPageFilter.Text = "Page Filter"
        Me.ckbPageFilter.UseVisualStyleBackColor = True
        '
        'GroupBox3
        '
        Me.GroupBox3.Controls.Add(Me.GroupBox4)
        Me.GroupBox3.Controls.Add(Me.ckbColumnFilter)
        Me.GroupBox3.Controls.Add(Me.ckbRowFilter)
        Me.GroupBox3.Font = New System.Drawing.Font("Microsoft Sans Serif", 8.25!, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, CType(0, Byte))
        Me.GroupBox3.Location = New System.Drawing.Point(137, 165)
        Me.GroupBox3.Name = "GroupBox3"
        Me.GroupBox3.Size = New System.Drawing.Size(270, 92)
        Me.GroupBox3.TabIndex = 81
        Me.GroupBox3.TabStop = False
        Me.GroupBox3.Text = "Row And Column Field Filter"
        '
        'GroupBox4
        '
        Me.GroupBox4.Controls.Add(Me.rdbRCValueFilter)
        Me.GroupBox4.Controls.Add(Me.rdbRCMultileFilter)
        Me.GroupBox4.Controls.Add(Me.rdbRCLabelFilter)
        Me.GroupBox4.Font = New System.Drawing.Font("Microsoft Sans Serif", 8.25!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, CType(0, Byte))
        Me.GroupBox4.Location = New System.Drawing.Point(3, 36)
        Me.GroupBox4.Name = "GroupBox4"
        Me.GroupBox4.Size = New System.Drawing.Size(252, 50)
        Me.GroupBox4.TabIndex = 2
        Me.GroupBox4.TabStop = False
        '
        'rdbRCValueFilter
        '
        Me.rdbRCValueFilter.AutoSize = True
        Me.rdbRCValueFilter.Location = New System.Drawing.Point(115, 11)
        Me.rdbRCValueFilter.Name = "rdbRCValueFilter"
        Me.rdbRCValueFilter.Size = New System.Drawing.Size(106, 17)
        Me.rdbRCValueFilter.TabIndex = 2
        Me.rdbRCValueFilter.TabStop = True
        Me.rdbRCValueFilter.Text = "Apply Value Filter"
        Me.rdbRCValueFilter.UseVisualStyleBackColor = True
        '
        'rdbRCMultileFilter
        '
        Me.rdbRCMultileFilter.AutoSize = True
        Me.rdbRCMultileFilter.Location = New System.Drawing.Point(6, 31)
        Me.rdbRCMultileFilter.Name = "rdbRCMultileFilter"
        Me.rdbRCMultileFilter.Size = New System.Drawing.Size(115, 17)
        Me.rdbRCMultileFilter.TabIndex = 1
        Me.rdbRCMultileFilter.TabStop = True
        Me.rdbRCMultileFilter.Text = "Apply Multiple Filter"
        Me.rdbRCMultileFilter.UseVisualStyleBackColor = True
        '
        'rdbRCLabelFilter
        '
        Me.rdbRCLabelFilter.AutoSize = True
        Me.rdbRCLabelFilter.Location = New System.Drawing.Point(6, 11)
        Me.rdbRCLabelFilter.Name = "rdbRCLabelFilter"
        Me.rdbRCLabelFilter.Size = New System.Drawing.Size(105, 17)
        Me.rdbRCLabelFilter.TabIndex = 0
        Me.rdbRCLabelFilter.TabStop = True
        Me.rdbRCLabelFilter.Text = "Apply Label Filter"
        Me.rdbRCLabelFilter.UseVisualStyleBackColor = True
        '
        'ckbColumnFilter
        '
        Me.ckbColumnFilter.AutoSize = True
        Me.ckbColumnFilter.Font = New System.Drawing.Font("Microsoft Sans Serif", 8.25!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, CType(0, Byte))
        Me.ckbColumnFilter.Location = New System.Drawing.Point(118, 19)
        Me.ckbColumnFilter.Name = "ckbColumnFilter"
        Me.ckbColumnFilter.Size = New System.Drawing.Size(86, 17)
        Me.ckbColumnFilter.TabIndex = 1
        Me.ckbColumnFilter.Text = "Column Filter"
        Me.ckbColumnFilter.UseVisualStyleBackColor = True
        '
        'ckbRowFilter
        '
        Me.ckbRowFilter.AutoSize = True
        Me.ckbRowFilter.Font = New System.Drawing.Font("Microsoft Sans Serif", 8.25!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, CType(0, Byte))
        Me.ckbRowFilter.Location = New System.Drawing.Point(14, 18)
        Me.ckbRowFilter.Name = "ckbRowFilter"
        Me.ckbRowFilter.Size = New System.Drawing.Size(73, 17)
        Me.ckbRowFilter.TabIndex = 0
        Me.ckbRowFilter.Text = "Row Filter"
        Me.ckbRowFilter.UseVisualStyleBackColor = True
        '
        'rdbExcel2013
        '
        Me.rdbExcel2013.AutoSize = True
        Me.rdbExcel2013.Font = New System.Drawing.Font("Microsoft Sans Serif", 8.25!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, CType(0, Byte))
        Me.rdbExcel2013.Location = New System.Drawing.Point(187, 11)
        Me.rdbExcel2013.Name = "rdbExcel2013"
        Me.rdbExcel2013.Size = New System.Drawing.Size(78, 17)
        Me.rdbExcel2013.TabIndex = 2
        Me.rdbExcel2013.Text = "Excel 2013"
        Me.rdbExcel2013.UseVisualStyleBackColor = True
        '
        'PivotTable
        '
        Me.AutoScaleDimensions = New System.Drawing.SizeF(6.0!, 13.0!)
        Me.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font
        Me.BackColor = System.Drawing.Color.White
        Me.ClientSize = New System.Drawing.Size(419, 349)
        Me.Controls.Add(Me.GroupBox3)
        Me.Controls.Add(Me.GroupBox2)
        Me.Controls.Add(Me.btnCustomize)
        Me.Controls.Add(Me.groupBox1)
        Me.Controls.Add(Me.btnCreate)
        Me.Controls.Add(Me.label2)
        Me.Controls.Add(Me.pictureBox1)
        Me.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedSingle
        Me.Icon = CType(resources.GetObject("$this.Icon"), System.Drawing.Icon)
        Me.MaximizeBox = False
        Me.MinimizeBox = False
        Me.Name = "PivotTable"
        Me.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen
        Me.Text = "PivotTable"
        CType(Me.pictureBox1, System.ComponentModel.ISupportInitialize).EndInit()
        Me.groupBox1.ResumeLayout(False)
        Me.groupBox1.PerformLayout()
        Me.GroupBox2.ResumeLayout(False)
        Me.GroupBox2.PerformLayout()
        Me.GroupBox3.ResumeLayout(False)
        Me.GroupBox3.PerformLayout()
        Me.GroupBox4.ResumeLayout(False)
        Me.GroupBox4.PerformLayout()
        Me.ResumeLayout(False)

    End Sub
    Private WithEvents label2 As System.Windows.Forms.Label
    Private WithEvents pictureBox1 As System.Windows.Forms.PictureBox
    Private WithEvents btnCustomize As System.Windows.Forms.Button
    Private WithEvents groupBox1 As System.Windows.Forms.GroupBox
    Private WithEvents rdbExcel2010 As System.Windows.Forms.RadioButton
    Private WithEvents rdbExcel2007 As System.Windows.Forms.RadioButton
    Private WithEvents btnCreate As System.Windows.Forms.Button
    Friend WithEvents GroupBox2 As System.Windows.Forms.GroupBox
    Friend WithEvents ckbPageFilter As System.Windows.Forms.CheckBox
    Friend WithEvents GroupBox3 As System.Windows.Forms.GroupBox
    Friend WithEvents GroupBox4 As System.Windows.Forms.GroupBox
    Friend WithEvents rdbRCValueFilter As System.Windows.Forms.RadioButton
    Friend WithEvents rdbRCMultileFilter As System.Windows.Forms.RadioButton
    Friend WithEvents rdbRCLabelFilter As System.Windows.Forms.RadioButton
    Friend WithEvents ckbColumnFilter As System.Windows.Forms.CheckBox
    Friend WithEvents ckbRowFilter As System.Windows.Forms.CheckBox
    Friend WithEvents ckbMultiplePageFilter As System.Windows.Forms.CheckBox
    Private WithEvents rdbExcel2013 As System.Windows.Forms.RadioButton

End Class
