'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.5456
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------


Imports Microsoft.VisualBasic
Imports System

Namespace My.Resources


	''' <summary>
	'''   A strongly-typed resource class, for looking up localized strings, etc.
	''' </summary>
	' This class was auto-generated by the StronglyTypedResourceBuilder
	' class via a tool like ResGen or Visual Studio.
	' To add or remove a member, edit your .ResX file then rerun ResGen
	' with the /str option, or rebuild your VS project.
	<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"), Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(), _
	Global.Microsoft.VisualBasic.HideModuleNameAttribute()> _
	Friend Module Resources

		Private resourceMan As Global.System.Resources.ResourceManager

		Private resourceCulture As Global.System.Globalization.CultureInfo

'		internal Resources()
'		{
'		}

		''' <summary>
		'''   Returns the cached ResourceManager instance used by this class.
		''' </summary>
		<Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
		Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
			Get
				If Object.ReferenceEquals(resourceMan, Nothing) Then
					Dim temp As New Global.System.Resources.ResourceManager("Resources", GetType(Resources).Assembly)
					resourceMan = temp
				End If
				Return resourceMan
			End Get
		End Property

		''' <summary>
		'''   Overrides the current thread's CurrentUICulture property for all
		'''   resource lookups using this strongly typed resource class.
		''' </summary>
		<Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
		Friend Property Culture() As Global.System.Globalization.CultureInfo
			Get
				Return resourceCulture
			End Get
			Set(ByVal value As System.Globalization.CultureInfo)
				resourceCulture = value
			End Set
		End Property

		Friend ReadOnly Property BlankPage32() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("BlankPage32", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property Bold16() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("Bold16", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property ClearFormatting16() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("ClearFormatting16", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property Close32() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("Close32", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property CoverPage32() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("CoverPage32", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property [Exit]() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("Exit", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property FontColor16() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("FontColor16", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property GrowFont16() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("GrowFont16", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property Italic16() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("Italic16", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property Open32() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("Open32", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property Options() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("Options", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property PageBreak32() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("PageBreak32", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property Picture32() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("Picture32", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property Save16() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("Save16", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property Save32() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("Save32", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property SaveAs32() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("SaveAs32", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property ShrinkFont16() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("ShrinkFont16", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property Strikethrough16() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("Strikethrough16", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property Subscript16() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("Subscript16", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property Superscript16() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("Superscript16", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property TextHighlightColor16() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("TextHighlightColor16", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property TextHighlightColor161() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("TextHighlightColor161", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		Friend ReadOnly Property Underline16() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("Underline16", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property
	End Module
End Namespace
