#Region "Copyright Syncfusion Inc. 2001 - 2005"
'
'  Copyright Syncfusion Inc. 2001 - 2005. All rights reserved.
'
'  Use of this code is subject to the terms of our license.
'  A copy of the current license can be obtained at any time by e-mailing
'  licensing@syncfusion.com. Re-distribution in any form is strictly
'  prohibited. Any infringement will be prosecuted under applicable laws. 
'
#End Region


Imports Microsoft.VisualBasic
Imports System
Imports System.Drawing
Imports System.Drawing.Imaging
Imports System.Collections
Imports System.ComponentModel
Imports System.Windows.Forms
Imports System.Data
Imports Syncfusion.Pdf
Imports Syncfusion.Pdf.Interactive
Imports Syncfusion.Pdf.Parsing


Namespace EssentialPDFSamples
	''' <summary>
	''' Summary description for Form1.
	''' </summary>
	Public Class Form1 : Inherits System.Windows.Forms.Form
		Private WithEvents btnPDFForm As System.Windows.Forms.Button
		Private label1 As System.Windows.Forms.Label
        Private WithEvents btnViewTemplate As Button
        Private WithEvents PictureBox2 As System.Windows.Forms.PictureBox

        ''' <summary>
        ''' Required designer variable.
        ''' </summary>
        Private components As System.ComponentModel.Container = Nothing

        Public Sub New()
            '
            ' Required for Windows Form Designer support
            '
            InitializeComponent()

            '
            ' TODO: Add any constructor code after InitializeComponent call
            ''
        End Sub

        ''' <summary>
        ''' Clean up any resources being used.
        ''' </summary>
        Protected Overloads Overrides Sub Dispose(ByVal disposing As Boolean)
            If disposing Then
                If Not components Is Nothing Then
                    components.Dispose()
                End If
            End If
            MyBase.Dispose(disposing)
        End Sub

#Region "Windows Form Designer generated code"
        ''' <summary>
        ''' Required method for Designer support - do not modify
        ''' the contents of this method with the code editor.
        ''' </summary>
        Private Sub InitializeComponent()
            Dim resources As System.ComponentModel.ComponentResourceManager = New System.ComponentModel.ComponentResourceManager(GetType(Form1))
            Me.btnPDFForm = New System.Windows.Forms.Button
            Me.label1 = New System.Windows.Forms.Label
            Me.btnViewTemplate = New System.Windows.Forms.Button
            Me.PictureBox2 = New System.Windows.Forms.PictureBox
            CType(Me.PictureBox2, System.ComponentModel.ISupportInitialize).BeginInit()
            Me.SuspendLayout()
            '
            'btnPDFForm
            '
            Me.btnPDFForm.Anchor = CType((System.Windows.Forms.AnchorStyles.Top Or System.Windows.Forms.AnchorStyles.Right), System.Windows.Forms.AnchorStyles)
            Me.btnPDFForm.BackColor = System.Drawing.Color.Transparent
            Me.btnPDFForm.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(CType(CType(255, Byte), Integer), CType(CType(192, Byte), Integer), CType(CType(128, Byte), Integer))
            Me.btnPDFForm.FlatAppearance.MouseDownBackColor = System.Drawing.Color.FromArgb(CType(CType(255, Byte), Integer), CType(CType(224, Byte), Integer), CType(CType(192, Byte), Integer))
            Me.btnPDFForm.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(CType(CType(255, Byte), Integer), CType(CType(255, Byte), Integer), CType(CType(192, Byte), Integer))
            Me.btnPDFForm.Image = CType(resources.GetObject("btnPDFForm.Image"), System.Drawing.Image)
            Me.btnPDFForm.ImageAlign = System.Drawing.ContentAlignment.MiddleRight
            Me.btnPDFForm.Location = New System.Drawing.Point(290, 176)
            Me.btnPDFForm.Name = "btnPDFForm"
            Me.btnPDFForm.Size = New System.Drawing.Size(75, 23)
            Me.btnPDFForm.TabIndex = 0
            Me.btnPDFForm.Text = "PDF"
            Me.btnPDFForm.UseVisualStyleBackColor = False
            '
            'label1
            '
            Me.label1.Anchor = CType(((System.Windows.Forms.AnchorStyles.Top Or System.Windows.Forms.AnchorStyles.Left) _
                        Or System.Windows.Forms.AnchorStyles.Right), System.Windows.Forms.AnchorStyles)
            Me.label1.Font = New System.Drawing.Font("Verdana", 8.25!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, CType(0, Byte))
            Me.label1.ForeColor = System.Drawing.Color.FromArgb(CType(CType(0, Byte), Integer), CType(CType(0, Byte), Integer), CType(CType(64, Byte), Integer))
            Me.label1.Location = New System.Drawing.Point(0, 123)
            Me.label1.Name = "label1"
            Me.label1.Size = New System.Drawing.Size(376, 98)
            Me.label1.TabIndex = 1
            Me.label1.Text = "Click the button to view an PDF document generated by Essential PDF. Please note " & _
                "that Adobe Reader or its equivalent is required to view the resultant document."
            '
            'btnViewTemplate
            '
            Me.btnViewTemplate.FlatStyle = System.Windows.Forms.FlatStyle.System
            Me.btnViewTemplate.Location = New System.Drawing.Point(4, 175)
            Me.btnViewTemplate.Name = "btnViewTemplate"
            Me.btnViewTemplate.Size = New System.Drawing.Size(163, 23)
            Me.btnViewTemplate.TabIndex = 25
            Me.btnViewTemplate.Text = "View PDF Form template"
            Me.btnViewTemplate.UseVisualStyleBackColor = True
            '
            'PictureBox2
            '
            Me.PictureBox2.Dock = System.Windows.Forms.DockStyle.Top
            Me.PictureBox2.Image = CType(resources.GetObject("PictureBox2.Image"), System.Drawing.Image)
            Me.PictureBox2.Location = New System.Drawing.Point(0, 0)
            Me.PictureBox2.Name = "PictureBox2"
            Me.PictureBox2.Size = New System.Drawing.Size(374, 90)
            Me.PictureBox2.TabIndex = 26
            Me.PictureBox2.TabStop = False
            '
            'Form1
            '
            Me.AutoScaleBaseSize = New System.Drawing.Size(5, 13)
            Me.BackColor = System.Drawing.Color.White
            Me.ClientSize = New System.Drawing.Size(374, 222)
            Me.Controls.Add(Me.PictureBox2)
            Me.Controls.Add(Me.btnViewTemplate)
            Me.Controls.Add(Me.btnPDFForm)
            Me.Controls.Add(Me.label1)
            Me.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedSingle
            Me.Icon = CType(resources.GetObject("$this.Icon"), System.Drawing.Icon)
            Me.MaximizeBox = False
            Me.MinimizeBox = False
            Me.Name = "Form1"
            Me.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen
            Me.Text = "Form Fill"
            CType(Me.PictureBox2, System.ComponentModel.ISupportInitialize).EndInit()
            Me.ResumeLayout(False)

        End Sub
#End Region

        ''' <summary>
        ''' The main entry point for the application.
        ''' </summary>
        <STAThread()> _
        Shared Sub Main()
            Application.EnableVisualStyles()
            Application.Run(New Form1())
        End Sub

        Private Sub btnPDFForm_Click(ByVal sender As Object, ByVal e As System.EventArgs) Handles btnPDFForm.Click
            'Load the template document
            Dim doc As PdfLoadedDocument = New PdfLoadedDocument("..\..\..\..\..\..\..\..\..\Common\Data\PDF\Form.pdf")

            Dim form As PdfLoadedForm = doc.Form

            ' fill the fields from the first page
            TryCast(form.Fields("f1-1"), PdfLoadedTextBoxField).Text = "1"
            TryCast(form.Fields("f1-2"), PdfLoadedTextBoxField).Text = "1"
            TryCast(form.Fields("f1-3"), PdfLoadedTextBoxField).Text = "1"
            TryCast(form.Fields("f1-4"), PdfLoadedTextBoxField).Text = "3"
            TryCast(form.Fields("f1-5"), PdfLoadedTextBoxField).Text = "1"
            TryCast(form.Fields("f1-6"), PdfLoadedTextBoxField).Text = "1"
            TryCast(form.Fields("f1-7"), PdfLoadedTextBoxField).Text = "22"
            TryCast(form.Fields("f1-8"), PdfLoadedTextBoxField).Text = "30"
            TryCast(form.Fields("f1-9"), PdfLoadedTextBoxField).Text = "John"
            TryCast(form.Fields("f1-10"), PdfLoadedTextBoxField).Text = "Doe"
            TryCast(form.Fields("f1-11"), PdfLoadedTextBoxField).Text = "3233 Spring Rd."
            TryCast(form.Fields("f1-12"), PdfLoadedTextBoxField).Text = "Atlanta, GA 30339"
            TryCast(form.Fields("f1-13"), PdfLoadedTextBoxField).Text = "332"
            TryCast(form.Fields("f1-14"), PdfLoadedTextBoxField).Text = "43"
            TryCast(form.Fields("f1-15"), PdfLoadedTextBoxField).Text = "4556"
            TryCast(form.Fields("f1-16"), PdfLoadedTextBoxField).Text = "3"
            TryCast(form.Fields("f1-17"), PdfLoadedTextBoxField).Text = "2000"
            TryCast(form.Fields("f1-18"), PdfLoadedTextBoxField).Text = "Exempt"
            TryCast(form.Fields("f1-19"), PdfLoadedTextBoxField).Text = "Syncfusion, Inc."
            TryCast(form.Fields("f1-20"), PdfLoadedTextBoxField).Text = "200"
            TryCast(form.Fields("f1-21"), PdfLoadedTextBoxField).Text = "22"
            TryCast(form.Fields("f1-22"), PdfLoadedTextBoxField).Text = "56654"
            TryCast(form.Fields("c1-1[0]"), PdfLoadedCheckBoxField).Items(0).Checked = True
            TryCast(form.Fields("c1-1[1]"), PdfLoadedCheckBoxField).Items(0).Checked = True

            ' fill the fields from the second page
            TryCast(form.Fields("f2-1"), PdfLoadedTextBoxField).Text = "3200"
            TryCast(form.Fields("f2-2"), PdfLoadedTextBoxField).Text = "4850"
            TryCast(form.Fields("f2-3"), PdfLoadedTextBoxField).Text = "0"
            TryCast(form.Fields("f2-4"), PdfLoadedTextBoxField).Text = "500"
            TryCast(form.Fields("f2-5"), PdfLoadedTextBoxField).Text = "500"
            TryCast(form.Fields("f2-6"), PdfLoadedTextBoxField).Text = "800"
            TryCast(form.Fields("f2-7"), PdfLoadedTextBoxField).Text = "0"
            TryCast(form.Fields("f2-8"), PdfLoadedTextBoxField).Text = "0"
            TryCast(form.Fields("f2-9"), PdfLoadedTextBoxField).Text = "3"
            TryCast(form.Fields("f2-10"), PdfLoadedTextBoxField).Text = "3"
            TryCast(form.Fields("f2-11"), PdfLoadedTextBoxField).Text = "3"
            TryCast(form.Fields("f2-12"), PdfLoadedTextBoxField).Text = "2"
            TryCast(form.Fields("f2-13"), PdfLoadedTextBoxField).Text = "3"
            TryCast(form.Fields("f2-14"), PdfLoadedTextBoxField).Text = "3"
            TryCast(form.Fields("f2-15"), PdfLoadedTextBoxField).Text = "2"
            TryCast(form.Fields("f2-16"), PdfLoadedTextBoxField).Text = "1"
            TryCast(form.Fields("f2-17"), PdfLoadedTextBoxField).Text = "200"
            TryCast(form.Fields("f2-18"), PdfLoadedTextBoxField).Text = "600"
            TryCast(form.Fields("f2-19"), PdfLoadedTextBoxField).Text = "250"

            doc.Save("sample.pdf")

            'Message box confirmation to view the created PDF document.
            If MessageBox.Show("Do you want to view the PDF file?", "PDF File Created", MessageBoxButtons.YesNo, MessageBoxIcon.Information) = Windows.Forms.DialogResult.Yes Then
                'Launching the PDF file using the default Application.[Acrobat Reader]
                System.Diagnostics.Process.Start("Sample.pdf")
                Me.Close()
            Else
                ' Exit
                Me.Close()
            End If
        End Sub

        Private Sub btnViewTemplate_Click(ByVal sender As Object, ByVal e As EventArgs) Handles btnViewTemplate.Click
            System.Diagnostics.Process.Start("..\..\..\..\..\..\..\..\..\Common\Data\PDF\Form.pdf")
        End Sub

	End Class
End Namespace
