<Global.Microsoft.VisualBasic.CompilerServices.DesignerGenerated()> _
Partial Class PivotChart
    Inherits System.Windows.Forms.Form
#Region "Dispose"
    'Form overrides dispose to clean up the component list.
    <System.Diagnostics.DebuggerNonUserCode()> _
    Protected Overrides Sub Dispose(ByVal disposing As Boolean)
        If disposing AndAlso components IsNot Nothing Then
            components.Dispose()
        End If
        MyBase.Dispose(disposing)
    End Sub
#End Region
    'Required by the Windows Form Designer
    Private components As System.ComponentModel.IContainer

#Region "Windows Form Generated Code"
    'NOTE: The following procedure is required by the Windows Form Designer
    'It can be modified using the Windows Form Designer.  
    'Do not modify it using the code editor.
    <System.Diagnostics.DebuggerStepThrough()> _
    Private Sub InitializeComponent()
        Dim resources As System.ComponentModel.ComponentResourceManager = New System.ComponentModel.ComponentResourceManager(GetType(PivotChart))
        Me.label2 = New System.Windows.Forms.Label
        Me.pictureBox1 = New System.Windows.Forms.PictureBox
        Me.btnCreate = New System.Windows.Forms.Button
        Me.GroupBox1 = New System.Windows.Forms.GroupBox
        Me.rdbExcel2013 = New System.Windows.Forms.RadioButton
        Me.rdbExcel2010 = New System.Windows.Forms.RadioButton
        Me.rdbExcel2007 = New System.Windows.Forms.RadioButton
        CType(Me.pictureBox1, System.ComponentModel.ISupportInitialize).BeginInit()
        Me.GroupBox1.SuspendLayout()
        Me.SuspendLayout()
        '
        'label2
        '
        Me.label2.Font = New System.Drawing.Font("Verdana", 8.25!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, CType(161, Byte))
        Me.label2.ForeColor = System.Drawing.SystemColors.ControlText
        Me.label2.Location = New System.Drawing.Point(0, 109)
        Me.label2.Name = "label2"
        Me.label2.Size = New System.Drawing.Size(372, 48)
        Me.label2.TabIndex = 76
        Me.label2.Text = "Click the button to view an Excel spreadsheet generated by Essential XlsIO. Pleas" & _
            "e note that MS Excel Viewer or MS Excel is required to view the resultant docume" & _
            "nt."
        Me.label2.TextAlign = System.Drawing.ContentAlignment.MiddleLeft
        '
        'pictureBox1
        '
        Me.pictureBox1.Dock = System.Windows.Forms.DockStyle.Top
        Me.pictureBox1.Image = CType(resources.GetObject("pictureBox1.Image"), System.Drawing.Image)
        Me.pictureBox1.Location = New System.Drawing.Point(0, 0)
        Me.pictureBox1.Name = "pictureBox1"
        Me.pictureBox1.Size = New System.Drawing.Size(372, 96)
        Me.pictureBox1.TabIndex = 75
        Me.pictureBox1.TabStop = False
        '
        'btnCreate
        '
        Me.btnCreate.Anchor = CType((System.Windows.Forms.AnchorStyles.Top Or System.Windows.Forms.AnchorStyles.Right), System.Windows.Forms.AnchorStyles)
        Me.btnCreate.BackColor = System.Drawing.Color.Transparent
        Me.btnCreate.Image = CType(resources.GetObject("btnCreate.Image"), System.Drawing.Image)
        Me.btnCreate.ImageAlign = System.Drawing.ContentAlignment.MiddleRight
        Me.btnCreate.Location = New System.Drawing.Point(278, 167)
        Me.btnCreate.Name = "btnCreate"
        Me.btnCreate.Size = New System.Drawing.Size(82, 26)
        Me.btnCreate.TabIndex = 74
        Me.btnCreate.Text = "Create"
        Me.btnCreate.UseVisualStyleBackColor = False
        '
        'GroupBox1
        '
        Me.GroupBox1.Controls.Add(Me.rdbExcel2013)
        Me.GroupBox1.Controls.Add(Me.rdbExcel2010)
        Me.GroupBox1.Controls.Add(Me.rdbExcel2007)
        Me.GroupBox1.Location = New System.Drawing.Point(3, 160)
        Me.GroupBox1.Name = "GroupBox1"
        Me.GroupBox1.Size = New System.Drawing.Size(269, 36)
        Me.GroupBox1.TabIndex = 77
        Me.GroupBox1.TabStop = False
        Me.GroupBox1.Text = "SaveAs"
        '
        'rdbExcel2013
        '
        Me.rdbExcel2013.AutoSize = True
        Me.rdbExcel2013.Location = New System.Drawing.Point(178, 13)
        Me.rdbExcel2013.Name = "rdbExcel2013"
        Me.rdbExcel2013.Size = New System.Drawing.Size(78, 17)
        Me.rdbExcel2013.TabIndex = 2
        Me.rdbExcel2013.Text = "Excel 2013"
        Me.rdbExcel2013.UseVisualStyleBackColor = True
        '
        'rdbExcel2010
        '
        Me.rdbExcel2010.AutoSize = True
        Me.rdbExcel2010.Location = New System.Drawing.Point(94, 13)
        Me.rdbExcel2010.Name = "rdbExcel2010"
        Me.rdbExcel2010.Size = New System.Drawing.Size(78, 17)
        Me.rdbExcel2010.TabIndex = 1
        Me.rdbExcel2010.Text = "Excel 2010"
        Me.rdbExcel2010.UseVisualStyleBackColor = True
        '
        'rdbExcel2007
        '
        Me.rdbExcel2007.AutoSize = True
        Me.rdbExcel2007.Checked = True
        Me.rdbExcel2007.Location = New System.Drawing.Point(12, 13)
        Me.rdbExcel2007.Name = "rdbExcel2007"
        Me.rdbExcel2007.Size = New System.Drawing.Size(78, 17)
        Me.rdbExcel2007.TabIndex = 0
        Me.rdbExcel2007.TabStop = True
        Me.rdbExcel2007.Text = "Excel 2007"
        Me.rdbExcel2007.UseVisualStyleBackColor = True
        '
        'PivotChart
        '
        Me.AutoScaleDimensions = New System.Drawing.SizeF(6.0!, 13.0!)
        Me.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font
        Me.BackColor = System.Drawing.Color.White
        Me.ClientSize = New System.Drawing.Size(372, 205)
        Me.Controls.Add(Me.GroupBox1)
        Me.Controls.Add(Me.label2)
        Me.Controls.Add(Me.pictureBox1)
        Me.Controls.Add(Me.btnCreate)
        Me.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedSingle
        Me.Icon = CType(resources.GetObject("$this.Icon"), System.Drawing.Icon)
        Me.MaximizeBox = False
        Me.MinimizeBox = False
        Me.Name = "PivotChart"
        Me.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen
        Me.Text = "PivotChart"
        CType(Me.pictureBox1, System.ComponentModel.ISupportInitialize).EndInit()
        Me.GroupBox1.ResumeLayout(False)
        Me.GroupBox1.PerformLayout()
        Me.ResumeLayout(False)

    End Sub
#End Region

#Region "Fields"
    Private WithEvents label2 As System.Windows.Forms.Label
    Private WithEvents pictureBox1 As System.Windows.Forms.PictureBox
    Private WithEvents btnCreate As System.Windows.Forms.Button
    Friend WithEvents GroupBox1 As System.Windows.Forms.GroupBox
    Friend WithEvents rdbExcel2010 As System.Windows.Forms.RadioButton
    Friend WithEvents rdbExcel2007 As System.Windows.Forms.RadioButton
    Friend WithEvents rdbExcel2013 As System.Windows.Forms.RadioButton
#End Region

End Class
