#Region "Copyright Syncfusion Inc. 2001 - 2013"
' Copyright Syncfusion Inc. 2001 - 2013. All rights reserved.
' Use of this code is subject to the terms of our license.
' A copy of the current license can be obtained at any time by e-mailing
' licensing@syncfusion.com. Any infringement will be prosecuted under
' applicable laws. 
#End Region

'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.42
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------


Imports Microsoft.VisualBasic
Imports System

Namespace My.Resources


	''' <summary>
	'''   A strongly-typed resource class, for looking up localized strings, etc.
	''' </summary>
	' This class was auto-generated by the StronglyTypedResourceBuilder
	' class via a tool like ResGen or Visual Studio.
	' To add or remove a member, edit your .ResX file then rerun ResGen
	' with the /str option, or rebuild your VS project.
    Friend Module Resources

        Private resourceMan As Global.System.Resources.ResourceManager

        Private resourceCulture As Global.System.Globalization.CultureInfo

        '		internal Resources()
        '		{
        '		}

        ''' <summary>
        '''   Returns the cached ResourceManager instance used by this class.
        ''' </summary>
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As New Global.System.Resources.ResourceManager("Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property

        ''' <summary>
        '''   Overrides the current thread's CurrentUICulture property for all
        '''   resource lookups using this strongly typed resource class.
        ''' </summary>
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set(ByVal value As System.Globalization.CultureInfo)
                resourceCulture = value
            End Set
        End Property

        Friend ReadOnly Property addressbook() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("addressbook", resourceCulture)
                Return (CType(obj, System.Drawing.Bitmap))
            End Get
        End Property

        Friend ReadOnly Property appointment() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("appointment", resourceCulture)
                Return (CType(obj, System.Drawing.Bitmap))
            End Get
        End Property

        Friend ReadOnly Property attach() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("attach", resourceCulture)
                Return (CType(obj, System.Drawing.Bitmap))
            End Get
        End Property

        Friend ReadOnly Property attach_item() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("attach_item", resourceCulture)
                Return (CType(obj, System.Drawing.Bitmap))
            End Get
        End Property

        Friend ReadOnly Property boldhs() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("boldhs", resourceCulture)
                Return (CType(obj, System.Drawing.Bitmap))
            End Get
        End Property

        Friend ReadOnly Property bookmark_icon_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bookmark_icon_16", resourceCulture)
                Return (CType(obj, System.Drawing.Bitmap))
            End Get
        End Property

        Friend ReadOnly Property border_icon1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("border_icon1", resourceCulture)
                Return (CType(obj, System.Drawing.Bitmap))
            End Get
        End Property

        Friend ReadOnly Property border_icon10() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("border_icon10", resourceCulture)
                Return (CType(obj, System.Drawing.Bitmap))
            End Get
        End Property

        Friend ReadOnly Property border_icon11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("border_icon11", resourceCulture)
                Return (CType(obj, System.Drawing.Bitmap))
            End Get
        End Property

        Friend ReadOnly Property border_icon12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("border_icon12", resourceCulture)
                Return (CType(obj, System.Drawing.Bitmap))
            End Get
        End Property

        Friend ReadOnly Property border_icon14() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("border_icon14", resourceCulture)
                Return (CType(obj, System.Drawing.Bitmap))
            End Get
        End Property

        Friend ReadOnly Property border_icon15() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("border_icon15", resourceCulture)
                Return (CType(obj, System.Drawing.Bitmap))
            End Get
        End Property

        Friend ReadOnly Property border_icon2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("border_icon2", resourceCulture)
                Return (CType(obj, System.Drawing.Bitmap))
            End Get
        End Property

        Friend ReadOnly Property border_icon3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("border_icon3", resourceCulture)
                Return (CType(obj, System.Drawing.Bitmap))
            End Get
        End Property

        Friend ReadOnly Property border_icon4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("border_icon4", resourceCulture)
                Return (CType(obj, System.Drawing.Bitmap))
            End Get
        End Property

        Friend ReadOnly Property border_icon5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("border_icon5", resourceCulture)
                Return (CType(obj, System.Drawing.Bitmap))
            End Get
        End Property

        Friend ReadOnly Property border_icon6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("border_icon6", resourceCulture)
                Return (CType(obj, System.Drawing.Bitmap))
            End Get
        End Property

        Friend ReadOnly Property border_icon7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("border_icon7", resourceCulture)
                Return (CType(obj, System.Drawing.Bitmap))
            End Get
        End Property

        Friend ReadOnly Property border_icon8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("border_icon8", resourceCulture)
                Return (CType(obj, System.Drawing.Bitmap))
            End Get
        End Property

        Friend ReadOnly Property border_icon9() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("border_icon9", resourceCulture)
                Return (CType(obj, System.Drawing.Bitmap))
            End Get
        End Property

        Friend ReadOnly Property bullet_icon1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bullet_icon1", resourceCulture)
                Return (CType(obj, System.Drawing.Bitmap))
            End Get
        End Property

        Friend ReadOnly Property bullet_icon2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bullet_icon2", resourceCulture)
                Return (CType(obj, System.Drawing.Bitmap))
            End Get
        End Property

        Friend ReadOnly Property bullet_icon3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bullet_icon3", resourceCulture)
                Return (CType(obj, System.Drawing.Bitmap))
            End Get
        End Property

        Friend ReadOnly Property bullet_icon4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bullet_icon4", resourceCulture)
                Return (CType(obj, System.Drawing.Bitmap))
            End Get
        End Property

        Friend ReadOnly Property business_card() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("business_card", resourceCulture)
                Return (CType(obj, System.Drawing.Bitmap))
            End Get
        End Property

        Friend ReadOnly Property calender() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("calender", resourceCulture)
                Return (CType(obj, System.Drawing.Bitmap))
            End Get
        End Property

        Friend ReadOnly Property center_justity_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("center_justity_icon", resourceCulture)
                Return (CType(obj, System.Drawing.Bitmap))
            End Get
        End Property

        Friend ReadOnly Property chart_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("chart_icon", resourceCulture)
                Return (CType(obj, System.Drawing.Bitmap))
            End Get
        End Property

        Friend ReadOnly Property chart_icon_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("chart_icon_16", resourceCulture)
                Return (CType(obj, System.Drawing.Bitmap))
            End Get
        End Property

        Friend ReadOnly Property check_names() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("check_names", resourceCulture)
                Return (CType(obj, System.Drawing.Bitmap))
            End Get
        End Property

        Friend ReadOnly Property chooseform() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("chooseform", resourceCulture)
                Return (CType(obj, System.Drawing.Bitmap))
            End Get
        End Property

        Friend ReadOnly Property clipart_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("clipart_icon", resourceCulture)
                Return (CType(obj, System.Drawing.Bitmap))
            End Get
        End Property

        Friend ReadOnly Property close() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("close", resourceCulture)
                Return (CType(obj, System.Drawing.Bitmap))
            End Get
        End Property

        Friend ReadOnly Property color_icon_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("color_icon_16", resourceCulture)
                Return (CType(obj, System.Drawing.Bitmap))
            End Get
        End Property

        Friend ReadOnly Property contact() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("contact", resourceCulture)
                Return (CType(obj, System.Drawing.Bitmap))
            End Get
        End Property

        Friend ReadOnly Property copy_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("copy_icon", resourceCulture)
                Return (CType(obj, System.Drawing.Bitmap))
            End Get
        End Property

        Friend ReadOnly Property cut_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cut_icon", resourceCulture)
                Return (CType(obj, System.Drawing.Bitmap))
            End Get
        End Property

        Friend ReadOnly Property date_time_icon_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("date_time_icon_16", resourceCulture)
                Return (CType(obj, System.Drawing.Bitmap))
            End Get
        End Property

        Friend ReadOnly Property delay_delivery() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("delay_delivery", resourceCulture)
                Return (CType(obj, System.Drawing.Bitmap))
            End Get
        End Property

        Friend ReadOnly Property delete() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("delete", resourceCulture)
                Return (CType(obj, System.Drawing.Bitmap))
            End Get
        End Property

        Friend ReadOnly Property direct_repliesto() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("direct_repliesto", resourceCulture)
                Return (CType(obj, System.Drawing.Bitmap))
            End Get
        End Property

        Friend ReadOnly Property distributionlist() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("distributionlist", resourceCulture)
                Return (CType(obj, System.Drawing.Bitmap))
            End Get
        End Property

        Friend ReadOnly Property dropcap_icon_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dropcap_icon_16", resourceCulture)
                Return (CType(obj, System.Drawing.Bitmap))
            End Get
        End Property

        Friend ReadOnly Property editoroptions() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("editoroptions", resourceCulture)
                Return (CType(obj, System.Drawing.Bitmap))
            End Get
        End Property

        Friend ReadOnly Property effect_icon_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("effect_icon_16", resourceCulture)
                Return (CType(obj, System.Drawing.Bitmap))
            End Get
        End Property

        Friend ReadOnly Property envelope_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("envelope_icon", resourceCulture)
                Return (CType(obj, System.Drawing.Bitmap))
            End Get
        End Property

        Friend ReadOnly Property equation_icon_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("equation_icon_16", resourceCulture)
                Return (CType(obj, System.Drawing.Bitmap))
            End Get
        End Property

        Friend ReadOnly Property FindHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FindHS", resourceCulture)
                Return (CType(obj, System.Drawing.Bitmap))
            End Get
        End Property

        Friend ReadOnly Property flag() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("flag", resourceCulture)
                Return (CType(obj, System.Drawing.Bitmap))
            End Get
        End Property

        Friend ReadOnly Property folder() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("folder", resourceCulture)
                Return (CType(obj, System.Drawing.Bitmap))
            End Get
        End Property

        Friend ReadOnly Property font_icon_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("font_icon_16", resourceCulture)
                Return (CType(obj, System.Drawing.Bitmap))
            End Get
        End Property

        Friend ReadOnly Property format_painter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("format_painter", resourceCulture)
                Return (CType(obj, System.Drawing.Bitmap))
            End Get
        End Property

        Friend ReadOnly Property general_icon1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("general_icon1", resourceCulture)
                Return (CType(obj, System.Drawing.Bitmap))
            End Get
        End Property

        Friend ReadOnly Property general_icon6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("general_icon6", resourceCulture)
                Return (CType(obj, System.Drawing.Bitmap))
            End Get
        End Property

        Friend ReadOnly Property gotoicon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gotoicon", resourceCulture)
                Return (CType(obj, System.Drawing.Bitmap))
            End Get
        End Property

        Friend ReadOnly Property high_importance() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("high_importance", resourceCulture)
                Return (CType(obj, System.Drawing.Bitmap))
            End Get
        End Property

        Friend ReadOnly Property html() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("html", resourceCulture)
                Return (CType(obj, System.Drawing.Bitmap))
            End Get
        End Property

        Friend ReadOnly Property hyperlink_icon1_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hyperlink_icon1_16", resourceCulture)
                Return (CType(obj, System.Drawing.Bitmap))
            End Get
        End Property

        Friend ReadOnly Property IndentHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IndentHS", resourceCulture)
                Return (CType(obj, System.Drawing.Bitmap))
            End Get
        End Property

        Friend ReadOnly Property ItalicHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ItalicHS", resourceCulture)
                Return (CType(obj, System.Drawing.Bitmap))
            End Get
        End Property

        Friend ReadOnly Property justity_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("justity_icon", resourceCulture)
                Return (CType(obj, System.Drawing.Bitmap))
            End Get
        End Property

        Friend ReadOnly Property left_justity_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("left_justity_icon", resourceCulture)
                Return (CType(obj, System.Drawing.Bitmap))
            End Get
        End Property

        Friend ReadOnly Property line_spacing_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("line_spacing_icon", resourceCulture)
                Return (CType(obj, System.Drawing.Bitmap))
            End Get
        End Property

        Friend ReadOnly Property low_importance() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("low_importance", resourceCulture)
                Return (CType(obj, System.Drawing.Bitmap))
            End Get
        End Property

        Friend ReadOnly Property meetingrequest() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("meetingrequest", resourceCulture)
                Return (CType(obj, System.Drawing.Bitmap))
            End Get
        End Property

        Friend ReadOnly Property moveto() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("moveto", resourceCulture)
                Return (CType(obj, System.Drawing.Bitmap))
            End Get
        End Property

        Friend ReadOnly Property NewFolderHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NewFolderHS", resourceCulture)
                Return (CType(obj, System.Drawing.Bitmap))
            End Get
        End Property

        Friend ReadOnly Property newmailmessage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("newmailmessage", resourceCulture)
                Return (CType(obj, System.Drawing.Bitmap))
            End Get
        End Property

        Friend ReadOnly Property NewMessageHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NewMessageHS", resourceCulture)
                Return (CType(obj, System.Drawing.Bitmap))
            End Get
        End Property

        Friend ReadOnly Property note() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("note", resourceCulture)
                Return (CType(obj, System.Drawing.Bitmap))
            End Get
        End Property

        Friend ReadOnly Property object_icon_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("object_icon_16", resourceCulture)
                Return (CType(obj, System.Drawing.Bitmap))
            End Get
        End Property

        Friend ReadOnly Property OutdentHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("OutdentHS", resourceCulture)
                Return (CType(obj, System.Drawing.Bitmap))
            End Get
        End Property

        Friend ReadOnly Property page_color() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("page_color", resourceCulture)
                Return (CType(obj, System.Drawing.Bitmap))
            End Get
        End Property

        Friend ReadOnly Property painbucket_icon1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("painbucket_icon1", resourceCulture)
                Return (CType(obj, System.Drawing.Bitmap))
            End Get
        End Property

        Friend ReadOnly Property painter_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("painter_icon", resourceCulture)
                Return (CType(obj, System.Drawing.Bitmap))
            End Get
        End Property

        Friend ReadOnly Property paste() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("paste", resourceCulture)
                Return (CType(obj, System.Drawing.Bitmap))
            End Get
        End Property

        Friend ReadOnly Property pasteicon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pasteicon", resourceCulture)
                Return (CType(obj, System.Drawing.Bitmap))
            End Get
        End Property

        Friend ReadOnly Property pastespecial() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pastespecial", resourceCulture)
                Return (CType(obj, System.Drawing.Bitmap))
            End Get
        End Property

        Friend ReadOnly Property picture_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("picture_icon", resourceCulture)
                Return (CType(obj, System.Drawing.Bitmap))
            End Get
        End Property

        Friend ReadOnly Property plain_text() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("plain_text", resourceCulture)
                Return (CType(obj, System.Drawing.Bitmap))
            End Get
        End Property

        Friend ReadOnly Property print() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("print", resourceCulture)
                Return (CType(obj, System.Drawing.Bitmap))
            End Get
        End Property

        Friend ReadOnly Property PrintHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PrintHS", resourceCulture)
                Return (CType(obj, System.Drawing.Bitmap))
            End Get
        End Property

        Friend ReadOnly Property PrintPreviewHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PrintPreviewHS", resourceCulture)
                Return (CType(obj, System.Drawing.Bitmap))
            End Get
        End Property

        Friend ReadOnly Property PrintSetupHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PrintSetupHS", resourceCulture)
                Return (CType(obj, System.Drawing.Bitmap))
            End Get
        End Property

        Friend ReadOnly Property properties() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("properties", resourceCulture)
                Return (CType(obj, System.Drawing.Bitmap))
            End Get
        End Property

        Friend ReadOnly Property quickpart_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("quickpart_icon", resourceCulture)
                Return (CType(obj, System.Drawing.Bitmap))
            End Get
        End Property

        Friend ReadOnly Property research_icon_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("research_icon_16", resourceCulture)
                Return (CType(obj, System.Drawing.Bitmap))
            End Get
        End Property

        Friend ReadOnly Property richtext() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("richtext", resourceCulture)
                Return (CType(obj, System.Drawing.Bitmap))
            End Get
        End Property

        Friend ReadOnly Property right_justity_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("right_justity_icon", resourceCulture)
                Return (CType(obj, System.Drawing.Bitmap))
            End Get
        End Property

        Friend ReadOnly Property save() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("save", resourceCulture)
                Return (CType(obj, System.Drawing.Bitmap))
            End Get
        End Property

        Friend ReadOnly Property save_sentitem() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("save_sentitem", resourceCulture)
                Return (CType(obj, System.Drawing.Bitmap))
            End Get
        End Property

        Friend ReadOnly Property saveas() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("saveas", resourceCulture)
                Return (CType(obj, System.Drawing.Bitmap))
            End Get
        End Property

        Friend ReadOnly Property saveHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("saveHS", resourceCulture)
                Return (CType(obj, System.Drawing.Bitmap))
            End Get
        End Property

        Friend ReadOnly Property [select]() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("select", resourceCulture)
                Return (CType(obj, System.Drawing.Bitmap))
            End Get
        End Property

        Friend ReadOnly Property selectall() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("selectall", resourceCulture)
                Return (CType(obj, System.Drawing.Bitmap))
            End Get
        End Property

        Friend ReadOnly Property send() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("send", resourceCulture)
                Return (CType(obj, System.Drawing.Bitmap))
            End Get
        End Property

        Friend ReadOnly Property set_lang_icon_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("set_lang_icon_16", resourceCulture)
                Return (CType(obj, System.Drawing.Bitmap))
            End Get
        End Property

        Friend ReadOnly Property shapes_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("shapes_icon", resourceCulture)
                Return (CType(obj, System.Drawing.Bitmap))
            End Get
        End Property

        Friend ReadOnly Property show_bcc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("show_bcc", resourceCulture)
                Return (CType(obj, System.Drawing.Bitmap))
            End Get
        End Property

        Friend ReadOnly Property show_from() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("show_from", resourceCulture)
                Return (CType(obj, System.Drawing.Bitmap))
            End Get
        End Property

        Friend ReadOnly Property sig_icon_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sig_icon_16", resourceCulture)
                Return (CType(obj, System.Drawing.Bitmap))
            End Get
        End Property

        Friend ReadOnly Property signature() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("signature", resourceCulture)
                Return (CType(obj, System.Drawing.Bitmap))
            End Get
        End Property

        Friend ReadOnly Property smartart_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("smartart_icon", resourceCulture)
                Return (CType(obj, System.Drawing.Bitmap))
            End Get
        End Property

        Friend ReadOnly Property sort() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sort", resourceCulture)
                Return (CType(obj, System.Drawing.Bitmap))
            End Get
        End Property

        Friend ReadOnly Property SortUpHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SortUpHS", resourceCulture)
                Return (CType(obj, System.Drawing.Bitmap))
            End Get
        End Property

        Friend ReadOnly Property spell_check_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("spell_check_icon", resourceCulture)
                Return (CType(obj, System.Drawing.Bitmap))
            End Get
        End Property

        Friend ReadOnly Property spell_check_icon_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("spell_check_icon_16", resourceCulture)
                Return (CType(obj, System.Drawing.Bitmap))
            End Get
        End Property

        Friend ReadOnly Property spelling() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("spelling", resourceCulture)
                Return (CType(obj, System.Drawing.Bitmap))
            End Get
        End Property

        Friend ReadOnly Property symbol_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("symbol_icon", resourceCulture)
                Return (CType(obj, System.Drawing.Bitmap))
            End Get
        End Property

        Friend ReadOnly Property symbol_icon_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("symbol_icon_16", resourceCulture)
                Return (CType(obj, System.Drawing.Bitmap))
            End Get
        End Property

        Friend ReadOnly Property SymbolHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SymbolHS", resourceCulture)
                Return (CType(obj, System.Drawing.Bitmap))
            End Get
        End Property

        Friend ReadOnly Property syncfusion_logo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("syncfusion_logo", resourceCulture)
                Return (CType(obj, System.Drawing.Bitmap))
            End Get
        End Property

        Friend ReadOnly Property table_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("table_icon", resourceCulture)
                Return (CType(obj, System.Drawing.Bitmap))
            End Get
        End Property

        Friend ReadOnly Property TableHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TableHS", resourceCulture)
                Return (CType(obj, System.Drawing.Bitmap))
            End Get
        End Property

        Friend ReadOnly Property TaskHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TaskHS", resourceCulture)
                Return (CType(obj, System.Drawing.Bitmap))
            End Get
        End Property

        Friend ReadOnly Property text_icon_32_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("text_icon_32_1", resourceCulture)
                Return (CType(obj, System.Drawing.Bitmap))
            End Get
        End Property

        Friend ReadOnly Property text_icon_32_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("text_icon_32_2", resourceCulture)
                Return (CType(obj, System.Drawing.Bitmap))
            End Get
        End Property

        Friend ReadOnly Property text_icon10() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("text_icon10", resourceCulture)
                Return (CType(obj, System.Drawing.Bitmap))
            End Get
        End Property

        Friend ReadOnly Property text_icon13() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("text_icon13", resourceCulture)
                Return (CType(obj, System.Drawing.Bitmap))
            End Get
        End Property

        Friend ReadOnly Property text_icon14() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("text_icon14", resourceCulture)
                Return (CType(obj, System.Drawing.Bitmap))
            End Get
        End Property

        Friend ReadOnly Property text_icon15() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("text_icon15", resourceCulture)
                Return (CType(obj, System.Drawing.Bitmap))
            End Get
        End Property

        Friend ReadOnly Property text_icon16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("text_icon16", resourceCulture)
                Return (CType(obj, System.Drawing.Bitmap))
            End Get
        End Property

        Friend ReadOnly Property text_icon17() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("text_icon17", resourceCulture)
                Return (CType(obj, System.Drawing.Bitmap))
            End Get
        End Property

        Friend ReadOnly Property text_icon3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("text_icon3", resourceCulture)
                Return (CType(obj, System.Drawing.Bitmap))
            End Get
        End Property

        Friend ReadOnly Property text_icon4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("text_icon4", resourceCulture)
                Return (CType(obj, System.Drawing.Bitmap))
            End Get
        End Property

        Friend ReadOnly Property text_icon7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("text_icon7", resourceCulture)
                Return (CType(obj, System.Drawing.Bitmap))
            End Get
        End Property

        Friend ReadOnly Property text_icon9() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("text_icon9", resourceCulture)
                Return (CType(obj, System.Drawing.Bitmap))
            End Get
        End Property

        Friend ReadOnly Property textbox_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("textbox_icon", resourceCulture)
                Return (CType(obj, System.Drawing.Bitmap))
            End Get
        End Property

        Friend ReadOnly Property themes_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("themes_icon", resourceCulture)
                Return (CType(obj, System.Drawing.Bitmap))
            End Get
        End Property

        Friend ReadOnly Property thesau_icon_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("thesau_icon_16", resourceCulture)
                Return (CType(obj, System.Drawing.Bitmap))
            End Get
        End Property

        Friend ReadOnly Property translate_icon_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("translate_icon_16", resourceCulture)
                Return (CType(obj, System.Drawing.Bitmap))
            End Get
        End Property

        Friend ReadOnly Property vote() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("vote", resourceCulture)
                Return (CType(obj, System.Drawing.Bitmap))
            End Get
        End Property

        Friend ReadOnly Property word_count_icon_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("word_count_icon_16", resourceCulture)
                Return (CType(obj, System.Drawing.Bitmap))
            End Get
        End Property

        Friend ReadOnly Property wordart_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("wordart_icon", resourceCulture)
                Return (CType(obj, System.Drawing.Bitmap))
            End Get
        End Property

        Friend ReadOnly Property wordart_icon_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("wordart_icon_16", resourceCulture)
                Return (CType(obj, System.Drawing.Bitmap))
            End Get
        End Property

        Friend ReadOnly Property zoom_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("zoom_icon", resourceCulture)
                Return (CType(obj, System.Drawing.Bitmap))
            End Get
        End Property

        Friend ReadOnly Property ZoomHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ZoomHS", resourceCulture)
                Return (CType(obj, System.Drawing.Bitmap))
            End Get
        End Property
    End Module
End Namespace
