#Region "Copyright Syncfusion Inc. 2001 - 2013"
'
'  Copyright Syncfusion Inc. 2001 - 2013. All rights reserved.
'
'  Use of this code is subject to the terms of our license.
'  A copy of the current license can be obtained at any time by e-mailing
'  licensing@syncfusion.com. Any infringement will be prosecuted under
'  applicable laws. 
'
#End Region


Imports Microsoft.VisualBasic
Imports System
Imports System.Drawing
Imports System.Drawing.Imaging
Imports System.Collections
Imports System.ComponentModel
Imports System.Windows.Forms
Imports System.Data
Imports System.IO
Imports System.Diagnostics
Imports Syncfusion.DocIO
Imports Syncfusion.DocIO.DLS

Namespace EssentialDocIOSamples
	Public Class Form1
		Inherits System.Windows.Forms.Form
		#Region "Private Members"
        Private WithEvents toolTip1 As System.Windows.Forms.ToolTip
        Private WithEvents label2 As System.Windows.Forms.Label
        Private WithEvents pictureBox3 As System.Windows.Forms.PictureBox
        Private WithEvents Button2 As System.Windows.Forms.Button
        Private WithEvents button1 As System.Windows.Forms.Button
        Private WithEvents GroupBox2 As System.Windows.Forms.GroupBox
        Private WithEvents Label6 As System.Windows.Forms.Label
        Private WithEvents word2013RadioBtn As System.Windows.Forms.RadioButton
        Private WithEvents Label4 As System.Windows.Forms.Label
        Private WithEvents word2010RadioBtn As System.Windows.Forms.RadioButton
        Private WithEvents Label5 As System.Windows.Forms.Label
        Private WithEvents label24 As System.Windows.Forms.Label
        Private WithEvents word2003RadioBtn As System.Windows.Forms.RadioButton
        Private WithEvents word2007RadioBtn As System.Windows.Forms.RadioButton
        Private components As IContainer
#End Region

#Region "Constructor, Main and Dispose"
        ''' <summary>
        ''' Constructor
        ''' </summary>
        Public Sub New()
            '
            ' Required for Windows Form Designer support
            '
            InitializeComponent()
            '
            ' TODO: Add any constructor code after InitializeComponent call
            ''
        End Sub
        ''' <summary>
        ''' The main entry point for the application.
        ''' </summary>
        <STAThread()> _
        Shared Sub Main()
            Application.EnableVisualStyles()
            Application.Run(New Form1())
        End Sub
        ''' <summary>
        ''' Clean up any resources being used.
        ''' </summary>
        Protected Overloads Overrides Sub Dispose(ByVal disposing As Boolean)
            If disposing Then
                If Not components Is Nothing Then
                    components.Dispose()
                End If
            End If
            MyBase.Dispose(disposing)
        End Sub
#End Region

#Region "Windows Form Designer generated code"
        ''' <summary>
        ''' Required method for Designer support - do not modify
        ''' the contents of this method with the code editor.
        ''' </summary>
        Private Sub InitializeComponent()
            Me.components = New System.ComponentModel.Container()
            Dim resources As System.ComponentModel.ComponentResourceManager = New System.ComponentModel.ComponentResourceManager(GetType(Form1))
            Me.label2 = New System.Windows.Forms.Label()
            Me.toolTip1 = New System.Windows.Forms.ToolTip(Me.components)
            Me.Label6 = New System.Windows.Forms.Label()
            Me.Label4 = New System.Windows.Forms.Label()
            Me.Label5 = New System.Windows.Forms.Label()
            Me.label24 = New System.Windows.Forms.Label()
            Me.pictureBox3 = New System.Windows.Forms.PictureBox()
            Me.Button2 = New System.Windows.Forms.Button()
            Me.button1 = New System.Windows.Forms.Button()
            Me.GroupBox2 = New System.Windows.Forms.GroupBox()
            Me.word2013RadioBtn = New System.Windows.Forms.RadioButton()
            Me.word2010RadioBtn = New System.Windows.Forms.RadioButton()
            Me.word2003RadioBtn = New System.Windows.Forms.RadioButton()
            Me.word2007RadioBtn = New System.Windows.Forms.RadioButton()
            CType(Me.pictureBox3, System.ComponentModel.ISupportInitialize).BeginInit()
            Me.GroupBox2.SuspendLayout()
            Me.SuspendLayout()
            '
            'label2
            '
            Me.label2.Font = New System.Drawing.Font("Verdana", 8.25!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, CType(161, Byte))
            Me.label2.ForeColor = System.Drawing.SystemColors.ControlText
            Me.label2.Location = New System.Drawing.Point(0, 110)
            Me.label2.Name = "label2"
            Me.label2.Size = New System.Drawing.Size(370, 44)
            Me.label2.TabIndex = 81
            Me.label2.Text = "Click the button to view the Word document generated by Essential DocIO. Please n" & _
        "ote that MS Word Viewer or MS Word is required to view the resultant document."
            '
            'Label6
            '
            Me.Label6.Image = CType(resources.GetObject("Label6.Image"), System.Drawing.Image)
            Me.Label6.Location = New System.Drawing.Point(221, 48)
            Me.Label6.Name = "Label6"
            Me.Label6.Size = New System.Drawing.Size(20, 18)
            Me.Label6.TabIndex = 106
            Me.toolTip1.SetToolTip(Me.Label6, "Saves the document in Word 2013 format")
            '
            'Label4
            '
            Me.Label4.Image = CType(resources.GetObject("Label4.Image"), System.Drawing.Image)
            Me.Label4.Location = New System.Drawing.Point(106, 48)
            Me.Label4.Name = "Label4"
            Me.Label4.Size = New System.Drawing.Size(20, 18)
            Me.Label4.TabIndex = 104
            Me.toolTip1.SetToolTip(Me.Label4, "Saves the document in Word 2010 format")
            '
            'Label5
            '
            Me.Label5.Image = CType(resources.GetObject("Label5.Image"), System.Drawing.Image)
            Me.Label5.Location = New System.Drawing.Point(221, 20)
            Me.Label5.Name = "Label5"
            Me.Label5.Size = New System.Drawing.Size(20, 18)
            Me.Label5.TabIndex = 101
            Me.toolTip1.SetToolTip(Me.Label5, "Saves the document in Word 2007 format")
            '
            'label24
            '
            Me.label24.Image = CType(resources.GetObject("label24.Image"), System.Drawing.Image)
            Me.label24.Location = New System.Drawing.Point(106, 22)
            Me.label24.Name = "label24"
            Me.label24.Size = New System.Drawing.Size(20, 18)
            Me.label24.TabIndex = 100
            Me.toolTip1.SetToolTip(Me.label24, "Saves the document in Word 97-2003 format")
            '
            'pictureBox3
            '
            Me.pictureBox3.Dock = System.Windows.Forms.DockStyle.Top
            Me.pictureBox3.Image = CType(resources.GetObject("pictureBox3.Image"), System.Drawing.Image)
            Me.pictureBox3.Location = New System.Drawing.Point(0, 0)
            Me.pictureBox3.Name = "pictureBox3"
            Me.pictureBox3.Size = New System.Drawing.Size(379, 97)
            Me.pictureBox3.TabIndex = 79
            Me.pictureBox3.TabStop = False
            '
            'Button2
            '
            Me.Button2.Anchor = CType((System.Windows.Forms.AnchorStyles.Top Or System.Windows.Forms.AnchorStyles.Right), System.Windows.Forms.AnchorStyles)
            Me.Button2.BackColor = System.Drawing.Color.FromArgb(CType(CType(246, Byte), Integer), CType(CType(249, Byte), Integer), CType(CType(255, Byte), Integer))
            Me.Button2.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(CType(CType(255, Byte), Integer), CType(CType(192, Byte), Integer), CType(CType(128, Byte), Integer))
            Me.Button2.FlatAppearance.MouseDownBackColor = System.Drawing.Color.FromArgb(CType(CType(255, Byte), Integer), CType(CType(224, Byte), Integer), CType(CType(192, Byte), Integer))
            Me.Button2.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(CType(CType(255, Byte), Integer), CType(CType(255, Byte), Integer), CType(CType(192, Byte), Integer))
            Me.Button2.Image = CType(resources.GetObject("Button2.Image"), System.Drawing.Image)
            Me.Button2.ImageAlign = System.Drawing.ContentAlignment.MiddleRight
            Me.Button2.Location = New System.Drawing.Point(269, 219)
            Me.Button2.Name = "Button2"
            Me.Button2.Size = New System.Drawing.Size(98, 25)
            Me.Button2.TabIndex = 84
            Me.Button2.Text = "Custom Styles"
            Me.Button2.TextAlign = System.Drawing.ContentAlignment.MiddleLeft
            Me.Button2.UseVisualStyleBackColor = True
            '
            'button1
            '
            Me.button1.Anchor = CType((System.Windows.Forms.AnchorStyles.Top Or System.Windows.Forms.AnchorStyles.Right), System.Windows.Forms.AnchorStyles)
            Me.button1.BackColor = System.Drawing.Color.FromArgb(CType(CType(246, Byte), Integer), CType(CType(249, Byte), Integer), CType(CType(255, Byte), Integer))
            Me.button1.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(CType(CType(255, Byte), Integer), CType(CType(192, Byte), Integer), CType(CType(128, Byte), Integer))
            Me.button1.FlatAppearance.MouseDownBackColor = System.Drawing.Color.FromArgb(CType(CType(255, Byte), Integer), CType(CType(224, Byte), Integer), CType(CType(192, Byte), Integer))
            Me.button1.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(CType(CType(255, Byte), Integer), CType(CType(255, Byte), Integer), CType(CType(192, Byte), Integer))
            Me.button1.Image = CType(resources.GetObject("button1.Image"), System.Drawing.Image)
            Me.button1.ImageAlign = System.Drawing.ContentAlignment.MiddleRight
            Me.button1.Location = New System.Drawing.Point(269, 184)
            Me.button1.Name = "button1"
            Me.button1.Size = New System.Drawing.Size(98, 25)
            Me.button1.TabIndex = 83
            Me.button1.Text = "Built-in Styles"
            Me.button1.TextAlign = System.Drawing.ContentAlignment.MiddleLeft
            Me.button1.UseVisualStyleBackColor = True
            '
            'GroupBox2
            '
            Me.GroupBox2.Controls.Add(Me.Label6)
            Me.GroupBox2.Controls.Add(Me.word2013RadioBtn)
            Me.GroupBox2.Controls.Add(Me.Label4)
            Me.GroupBox2.Controls.Add(Me.word2010RadioBtn)
            Me.GroupBox2.Controls.Add(Me.Label5)
            Me.GroupBox2.Controls.Add(Me.label24)
            Me.GroupBox2.Controls.Add(Me.word2003RadioBtn)
            Me.GroupBox2.Controls.Add(Me.word2007RadioBtn)
            Me.GroupBox2.Font = New System.Drawing.Font("Verdana", 8.25!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, CType(0, Byte))
            Me.GroupBox2.Location = New System.Drawing.Point(3, 172)
            Me.GroupBox2.Name = "GroupBox2"
            Me.GroupBox2.Size = New System.Drawing.Size(251, 72)
            Me.GroupBox2.TabIndex = 101
            Me.GroupBox2.TabStop = False
            Me.GroupBox2.Text = "Save As"
            '
            'word2013RadioBtn
            '
            Me.word2013RadioBtn.AutoSize = True
            Me.word2013RadioBtn.Checked = True
            Me.word2013RadioBtn.Font = New System.Drawing.Font("Tahoma", 8.25!, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, CType(0, Byte))
            Me.word2013RadioBtn.Location = New System.Drawing.Point(139, 46)
            Me.word2013RadioBtn.Name = "word2013RadioBtn"
            Me.word2013RadioBtn.Size = New System.Drawing.Size(86, 17)
            Me.word2013RadioBtn.TabIndex = 105
            Me.word2013RadioBtn.TabStop = True
            Me.word2013RadioBtn.Text = "Word 2013"
            Me.word2013RadioBtn.UseVisualStyleBackColor = True
            '
            'word2010RadioBtn
            '
            Me.word2010RadioBtn.AutoSize = True
            Me.word2010RadioBtn.Font = New System.Drawing.Font("Tahoma", 8.25!, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, CType(0, Byte))
            Me.word2010RadioBtn.Location = New System.Drawing.Point(6, 46)
            Me.word2010RadioBtn.Name = "word2010RadioBtn"
            Me.word2010RadioBtn.Size = New System.Drawing.Size(86, 17)
            Me.word2010RadioBtn.TabIndex = 103
            Me.word2010RadioBtn.Text = "Word 2010"
            Me.word2010RadioBtn.UseVisualStyleBackColor = True
            '
            'word2003RadioBtn
            '
            Me.word2003RadioBtn.AutoSize = True
            Me.word2003RadioBtn.Font = New System.Drawing.Font("Tahoma", 8.25!, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, CType(161, Byte))
            Me.word2003RadioBtn.Location = New System.Drawing.Point(6, 20)
            Me.word2003RadioBtn.Name = "word2003RadioBtn"
            Me.word2003RadioBtn.Size = New System.Drawing.Size(105, 17)
            Me.word2003RadioBtn.TabIndex = 44
            Me.word2003RadioBtn.Text = "Word 97-2003"
            Me.word2003RadioBtn.UseVisualStyleBackColor = True
            '
            'word2007RadioBtn
            '
            Me.word2007RadioBtn.AutoSize = True
            Me.word2007RadioBtn.Font = New System.Drawing.Font("Tahoma", 8.25!, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, CType(161, Byte))
            Me.word2007RadioBtn.Location = New System.Drawing.Point(139, 20)
            Me.word2007RadioBtn.Name = "word2007RadioBtn"
            Me.word2007RadioBtn.Size = New System.Drawing.Size(86, 17)
            Me.word2007RadioBtn.TabIndex = 45
            Me.word2007RadioBtn.Text = "Word 2007"
            Me.word2007RadioBtn.UseVisualStyleBackColor = True
            '
            'Form1
            '
            Me.AutoScaleBaseSize = New System.Drawing.Size(5, 13)
            Me.BackColor = System.Drawing.Color.White
            Me.ClientSize = New System.Drawing.Size(379, 263)
            Me.Controls.Add(Me.GroupBox2)
            Me.Controls.Add(Me.Button2)
            Me.Controls.Add(Me.button1)
            Me.Controls.Add(Me.label2)
            Me.Controls.Add(Me.pictureBox3)
            Me.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedSingle
            Me.Icon = CType(resources.GetObject("$this.Icon"), System.Drawing.Icon)
            Me.MaximizeBox = False
            Me.Name = "Form1"
            Me.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen
            Me.Text = " Styles"
            CType(Me.pictureBox3, System.ComponentModel.ISupportInitialize).EndInit()
            Me.GroupBox2.ResumeLayout(False)
            Me.GroupBox2.PerformLayout()
            Me.ResumeLayout(False)

        End Sub
#End Region

#Region "Button_Click Event"
        ''' <summary>
        ''' Creates word document with built - in styles
        ''' </summary>
        ''' <param name="sender"></param>
        ''' <param name="e"></param>
        Private Sub button1_Click(ByVal sender As Object, ByVal e As System.EventArgs)

        End Sub
#End Region

        Private Sub Button2_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles Button2.Click
            'Create a new document
            Dim document As WordDocument = New WordDocument()
            Dim style As IWParagraphStyle = Nothing
            ' Adding a new section to the document.
            Dim section As WSection = TryCast(document.AddSection(), WSection)
            'Set Margin of the Section
            section.PageSetup.Margins.All = 72
            Dim par As IWParagraph = document.LastSection.AddParagraph()
            Dim range As WTextRange = TryCast(par.AppendText("Using CustomStyles"), WTextRange)
            range.CharacterFormat.TextBackgroundColor = System.Drawing.Color.Blue
            range.CharacterFormat.FontSize = 18.0F
            document.LastParagraph.ParagraphFormat.HorizontalAlignment = Syncfusion.DocIO.DLS.HorizontalAlignment.Center

            ' Create Paragraph styles
            style = document.AddParagraphStyle("MyStyle_Normal")
            style.CharacterFormat.FontName = "Bitstream Vera Serif"
            style.CharacterFormat.FontSize = 10.0F
            style.ParagraphFormat.HorizontalAlignment = Syncfusion.DocIO.DLS.HorizontalAlignment.Justify
            style.CharacterFormat.TextColor = Color.FromArgb(0, 21, 84)

            style = document.AddParagraphStyle("MyStyle_Low")
            style.CharacterFormat.FontName = "Times New Roman"
            style.CharacterFormat.FontSize = 16.0F
            style.CharacterFormat.Bold = True

            style = document.AddParagraphStyle("MyStyle_Medium")
            style.CharacterFormat.FontName = "Monotype Corsiva"
            style.CharacterFormat.FontSize = 18.0F
            style.CharacterFormat.Bold = True
            style.CharacterFormat.TextColor = Color.FromArgb(51, 66, 125)

            style = document.AddParagraphStyle("Mystyle_High")
            style.CharacterFormat.FontName = "Bitstream Vera Serif"
            style.CharacterFormat.FontSize = 20.0F
            style.CharacterFormat.Bold = True
            style.CharacterFormat.TextColor = Color.FromArgb(242, 151, 50)

            Dim paragraph As IWParagraph = Nothing
            Dim i As Integer = 1
            'ORIGINAL LINE: for (int i = 1 ; i < document.Styles.Count ; i += 1)
            'INSTANT VB NOTE: This 'for' loop was translated to a VB 'Do While' loop:
            Do While i < document.Styles.Count
                ' Getting styles from Document.
                style = CType(document.Styles(i), IWParagraphStyle)
                ' Adding a new paragraph
                section.AddParagraph()
                paragraph = section.AddParagraph()
                ' Applying styles to the current paragraph.
                paragraph.ApplyStyle(style.Name)
                ' Writing Text with the current style and formatting.
                paragraph.AppendText("Syncfusion Inc [" & style.Name & "] Style")
                ' Adding a new paragraph
                section.AddParagraph()
                paragraph = section.AddParagraph()
                ' Applying another style to the current paragraph.
                paragraph.ApplyStyle("MyStyle_Normal")
                ' Writing text with current style.
                paragraph.AppendText("We are a leading provider of software components and tools for the Microsoft .NET platform. Powerful and feature-rich, Syncfusion�s broad range of products are vital to mission-critical applications in organizations ranging from small businesses to multinational Fortune 100 companies. ")
                i += 1
            Loop

            'Save as word 2003  format
            If word2003RadioBtn.Checked Then
                'Saving the document to disk.
                document.Save("Sample.doc")

                'Message box confirmation to view the created document.
                If MessageBox.Show("Do you want to view the MS Word document?", "Document has been created", MessageBoxButtons.YesNo, MessageBoxIcon.Information) = DialogResult.Yes Then
                    'Launching the MS Word file using the default Application.[MS Word Or Free WordViewer]
                    System.Diagnostics.Process.Start("Sample.doc")
                    'Exit
                    Me.Close()
                End If
                'Save as word 2007 format
            ElseIf word2007RadioBtn.Checked Then

                'Saving the document as .docx
                document.Save("Sample.docx", FormatType.Word2007)
                'Message box confirmation to view the created document.
                If MessageBox.Show("Do you want to view the MS Word document?", "Document has been created", MessageBoxButtons.YesNo, MessageBoxIcon.Information) = DialogResult.Yes Then
                    Try
                        'Launching the MS Word file using the default Application.[MS Word Or Free WordViewer]
                        System.Diagnostics.Process.Start("Sample.docx")
                        'Exit
                        Me.Close()
                    Catch ex As Win32Exception
                        MessageBox.Show("Word 2007 is not installed in this system")
                        Console.WriteLine(ex.ToString())
                    End Try
                End If
                'Save as word 2010 format
            ElseIf word2010RadioBtn.Checked Then

                'Saving the document as .docx
                document.Save("Sample.docx", FormatType.Word2010)
                'Message box confirmation to view the created document.
                If MessageBox.Show("Do you want to view the MS Word document?", "Document has been created", MessageBoxButtons.YesNo, MessageBoxIcon.Information) = DialogResult.Yes Then
                    Try
                        'Launching the MS Word file using the default Application.[MS Word Or Free WordViewer]
                        System.Diagnostics.Process.Start("Sample.docx")
                        'Exit
                        Me.Close()
                    Catch ex As Win32Exception
                        MessageBox.Show("Word 2007 is not installed in this system")
                        Console.WriteLine(ex.ToString())
                    End Try
                End If
                'Save as word 2013 format
            ElseIf word2013RadioBtn.Checked Then

                'Saving the document as .docx
                document.Save("Sample.docx", FormatType.Word2013)
                'Message box confirmation to view the created document.
                If MessageBox.Show("Do you want to view the MS Word document?", "Document has been created", MessageBoxButtons.YesNo, MessageBoxIcon.Information) = DialogResult.Yes Then
                    Try
                        'Launching the MS Word file using the default Application.[MS Word Or Free WordViewer]
                        System.Diagnostics.Process.Start("Sample.docx")
                        'Exit
                        Me.Close()
                    Catch ex As Win32Exception
                        MessageBox.Show("Word 2013 is not installed in this system")
                        Console.WriteLine(ex.ToString())
                    End Try
                End If
            Else
                ' Exit
                Me.Close()
            End If
        End Sub

        Private Sub button1_Click_1(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles button1.Click
            Dim document As WordDocument = New WordDocument()
            Dim section As WSection = TryCast(document.AddSection(), WSection)
            Dim para As WParagraph = TryCast(section.AddParagraph(), WParagraph)
            'Set Margin of the Section
            section.PageSetup.Margins.All = 72
            section.AddColumn(100, 100)
            section.AddColumn(100, 100)
            section.MakeColumnsEqual()

            '			#Region "List Style"

            'List
            'para = section.AddParagraph() as WParagraph;
            para.AppendText("This para is written with style List").CharacterFormat.UnderlineStyle = UnderlineStyle.Double
            para = TryCast(section.AddParagraph(), WParagraph)
            para.ApplyStyle(BuiltinStyle.List)
            para.AppendText("Essential DocIO" & Constants.vbLf)
            para.AppendText("Essential PDF" & Constants.vbLf)
            para.AppendText("Essential XlsIO")

            'List5 style
            para = TryCast(section.AddParagraph(), WParagraph)
            para.AppendText(Constants.vbLf & "This para is written with style List5").CharacterFormat.UnderlineStyle = UnderlineStyle.Double
            para = TryCast(section.AddParagraph(), WParagraph)
            para.ApplyStyle(BuiltinStyle.List5)
            para.AppendText("Essential DocIO" & Constants.vbLf)
            para.AppendText("Essential PDF" & Constants.vbLf)
            para.AppendText("Essential XlsIO")

            '			#End Region

            '			#Region "ListNumber Style"

            'List Number style
            para = TryCast(section.AddParagraph(), WParagraph)
            para.AppendText(Constants.vbLf & "This para is written with style ListNumber").CharacterFormat.UnderlineStyle = UnderlineStyle.Double
            para = TryCast(section.AddParagraph(), WParagraph)
            para.ApplyStyle(BuiltinStyle.ListNumber)
            para.AppendText("Essential DocIO" & Constants.vbLf)
            para.AppendText("Essential PDF" & Constants.vbLf)
            para.AppendText("Essential XlsIO")

            'List Number5 style
            para = TryCast(section.AddParagraph(), WParagraph)
            para.AppendText(Constants.vbLf & "This para is written with style ListNumber5").CharacterFormat.UnderlineStyle = UnderlineStyle.Double
            para = TryCast(section.AddParagraph(), WParagraph)
            para.ApplyStyle(BuiltinStyle.ListNumber5)
            para.AppendText("Essential DocIO" & Constants.vbLf)
            para.AppendText("Essential PDF" & Constants.vbLf)
            para.AppendText("Essential XlsIO")

            '			#End Region

            '			#Region "TOA Heading Style"

            'TOA Heading
            para = TryCast(section.AddParagraph(), WParagraph)
            para.AppendText(Constants.vbLf & "This para is written with style TOA Heading").CharacterFormat.UnderlineStyle = UnderlineStyle.Double
            para = TryCast(section.AddParagraph(), WParagraph)
            para.ApplyStyle(BuiltinStyle.ToaHeading)
            para.AppendText("Essential DocIO" & Constants.vbLf)
            para.AppendText("Essential PDF" & Constants.vbLf)
            para.AppendText("Essential XlsIO")

            '			#End Region

            para = TryCast(section.AddParagraph(), WParagraph)
            section.BreakCode = SectionBreakCode.NewColumn

            '			#Region "ListBullet Style"
            'ListBullet
            para = TryCast(section.AddParagraph(), WParagraph)
            para.AppendText(Constants.vbLf & "This para is written with style ListBullet").CharacterFormat.UnderlineStyle = UnderlineStyle.Double
            para = TryCast(section.AddParagraph(), WParagraph)
            para.ApplyStyle(BuiltinStyle.ListBullet)
            para.AppendText("Essential DocIO" & Constants.vbLf)
            para.AppendText("Essential PDF" & Constants.vbLf)
            para.AppendText("Essential XlsIO")

            'ListBullet5
            para = TryCast(section.AddParagraph(), WParagraph)
            para.AppendText(Constants.vbLf & "This para is written with style ListBullet5").CharacterFormat.UnderlineStyle = UnderlineStyle.Double
            para = TryCast(section.AddParagraph(), WParagraph)
            para.ApplyStyle(BuiltinStyle.ListBullet5)
            para.AppendText("Essential DocIO" & Constants.vbLf)
            para.AppendText("Essential PDF" & Constants.vbLf)
            para.AppendText("Essential XlsIO")

            '			#End Region

            '			#Region "List Continue Style"

            'ListContinue
            para = TryCast(section.AddParagraph(), WParagraph)
            para.AppendText(Constants.vbLf & "This para is written with style ListContinue").CharacterFormat.UnderlineStyle = UnderlineStyle.Double
            para = TryCast(section.AddParagraph(), WParagraph)
            para.ApplyStyle(BuiltinStyle.ListContinue)
            para.AppendText("Essential DocIO" & Constants.vbLf)
            para.AppendText("Essential PDF" & Constants.vbLf)
            para.AppendText("Essential XlsIO")

            'ListContinue5
            para = TryCast(section.AddParagraph(), WParagraph)
            para.AppendText(Constants.vbLf & "This para is written with style ListContinue5").CharacterFormat.UnderlineStyle = UnderlineStyle.Double
            para = TryCast(section.AddParagraph(), WParagraph)
            para.ApplyStyle(BuiltinStyle.ListContinue5)
            para.AppendText("Essential DocIO" & Constants.vbLf)
            para.AppendText("Essential PDF" & Constants.vbLf)
            para.AppendText("Essential XlsIO")

            '			#End Region

            '			#Region "HTMLSample Style"

            'HtmlSample
            para = TryCast(section.AddParagraph(), WParagraph)
            para.AppendText(Constants.vbLf & "This para is written with style HtmlSample").CharacterFormat.UnderlineStyle = UnderlineStyle.Double
            para = TryCast(section.AddParagraph(), WParagraph)
            para.ApplyStyle(BuiltinStyle.HtmlSample)
            para.AppendText("Essential DocIO" & Constants.vbLf)
            para.AppendText("Essential PDF" & Constants.vbLf)
            para.AppendText("Essential XlsIO")

            '			#End Region

            section = TryCast(document.AddSection(), WSection)
            section.BreakCode = SectionBreakCode.NoBreak

            '			#Region "Document Map Style"

            'Docuemnt Map
            para = TryCast(section.AddParagraph(), WParagraph)
            para.AppendText("This para is written with style DocumentMap" & Constants.vbLf).CharacterFormat.UnderlineStyle = UnderlineStyle.Double
            para = TryCast(section.AddParagraph(), WParagraph)
            para.ApplyStyle(BuiltinStyle.DocumentMap)
            para.AppendText("Essential DocIO" & Constants.vbLf)
            para.AppendText("Essential PDF" & Constants.vbLf)
            para.AppendText("Essential XlsIO")

            '			#End Region

            '			#Region "Heading Styles"
            'Heading Styles
            para = TryCast(section.AddParagraph(), WParagraph)
            para.ApplyStyle(BuiltinStyle.Heading1)
            para.AppendText("Hello World. This para is written with style " & para.StyleName.ToString())

            para = TryCast(section.AddParagraph(), WParagraph)
            para.ApplyStyle(BuiltinStyle.Heading2)
            para.AppendText("Hello World. This para is written with style " & para.StyleName.ToString())

            para = TryCast(section.AddParagraph(), WParagraph)
            para.ApplyStyle(BuiltinStyle.Heading3)
            para.AppendText("Hello World. This para is written with style " & para.StyleName.ToString())

            para = TryCast(section.AddParagraph(), WParagraph)
            para.ApplyStyle(BuiltinStyle.Heading4)
            para.AppendText("Hello World. This para is written with style " & para.StyleName.ToString())

            para = TryCast(section.AddParagraph(), WParagraph)
            para.ApplyStyle(BuiltinStyle.Heading5)
            para.AppendText("Hello World. This para is written with style " & para.StyleName.ToString())

            para = TryCast(section.AddParagraph(), WParagraph)
            para.ApplyStyle(BuiltinStyle.Heading6)
            para.AppendText("Hello World. This para is written with style " & para.StyleName.ToString())

            para = TryCast(section.AddParagraph(), WParagraph)
            para.ApplyStyle(BuiltinStyle.Heading7)
            para.AppendText("Hello World. This para is written with style " & para.StyleName.ToString())

            para = TryCast(section.AddParagraph(), WParagraph)
            para.ApplyStyle(BuiltinStyle.Heading8)
            para.AppendText("Hello World. This para is written with style " & para.StyleName.ToString())

            para = TryCast(section.AddParagraph(), WParagraph)
            para.ApplyStyle(BuiltinStyle.Heading9)
            para.AppendText("Hello World. This para is written with style " & para.StyleName.ToString())

            '			#End Region

            '			#Region "MessageHeaderStyle"

            'MessageHeader
            para = TryCast(section.AddParagraph(), WParagraph)
            para = TryCast(section.AddParagraph(), WParagraph)
            para.AppendText("This para is written with style MessageHeader" & Constants.vbLf).CharacterFormat.UnderlineStyle = UnderlineStyle.Double
            para = TryCast(section.AddParagraph(), WParagraph)
            para.ApplyStyle(BuiltinStyle.MessageHeader)
            para.AppendText("Essential DocIO" & Constants.vbLf)
            para.AppendText("Essential PDF" & Constants.vbLf)
            para.AppendText("Essential XlsIO")

            '			#End Region

            '			#Region "Save Document"

            'Save as word 2003  format
            If word2003RadioBtn.Checked Then
                'Saving the document to disk.
                document.Save("Sample.doc")

                'Message box confirmation to view the created document.
                If MessageBox.Show("Do you want to view the MS Word document?", "Document has been created", MessageBoxButtons.YesNo, MessageBoxIcon.Information) = DialogResult.Yes Then
                    'Launching the MS Word file using the default Application.[MS Word Or Free WordViewer]
                    System.Diagnostics.Process.Start("Sample.doc")
                    'Exit
                    Me.Close()
                End If
                'Save as word 2007 format
            ElseIf word2007RadioBtn.Checked Then

                'Saving the document as .docx
                document.Save("Sample.docx", FormatType.Word2007)
                'Message box confirmation to view the created document.
                If MessageBox.Show("Do you want to view the MS Word document?", "Document has been created", MessageBoxButtons.YesNo, MessageBoxIcon.Information) = DialogResult.Yes Then
                    Try
                        'Launching the MS Word file using the default Application.[MS Word Or Free WordViewer]
                        System.Diagnostics.Process.Start("Sample.docx")
                        'Exit
                        Me.Close()
                    Catch ex As Win32Exception
                        MessageBox.Show("Word 2007 is not installed in this system")
                        Console.WriteLine(ex.ToString())
                    End Try
                End If
                'Save as word 2010 format
            ElseIf word2010RadioBtn.Checked Then

                'Saving the document as .docx
                document.Save("Sample.docx", FormatType.Word2010)
                'Message box confirmation to view the created document.
                If MessageBox.Show("Do you want to view the MS Word document?", "Document has been created", MessageBoxButtons.YesNo, MessageBoxIcon.Information) = DialogResult.Yes Then
                    Try
                        'Launching the MS Word file using the default Application.[MS Word Or Free WordViewer]
                        System.Diagnostics.Process.Start("Sample.docx")
                        'Exit
                        Me.Close()
                    Catch ex As Win32Exception
                        MessageBox.Show("Word 2007 is not installed in this system")
                        Console.WriteLine(ex.ToString())
                    End Try
                End If
                'Save as word 2013 format
            ElseIf word2013RadioBtn.Checked Then

                'Saving the document as .docx
                document.Save("Sample.docx", FormatType.Word2013)
                'Message box confirmation to view the created document.
                If MessageBox.Show("Do you want to view the MS Word document?", "Document has been created", MessageBoxButtons.YesNo, MessageBoxIcon.Information) = DialogResult.Yes Then
                    Try
                        'Launching the MS Word file using the default Application.[MS Word Or Free WordViewer]
                        System.Diagnostics.Process.Start("Sample.docx")
                        'Exit
                        Me.Close()
                    Catch ex As Win32Exception
                        MessageBox.Show("Word 2013 is not installed in this system")
                        Console.WriteLine(ex.ToString())
                    End Try
                End If
            Else
                ' Exit
                Me.Close()
            End If
            '			#End Region
        End Sub
    End Class
End Namespace